### ISSUE TITLE
AttributeError: 'str' object has no attribute 'foramt'

### ISSUE THREAD

**Issue by Russel88** [MrOlm/drep#108]
Hi

I'm getting the following error during the secondary clustering, with fastANI. Using dRep v2.5.1. What could be the problem?

CRITICAL ERROR WITH SECONDARY CLUSTERING CODE aztqdxiitx; SKIPPING
Traceback (most recent call last):
  File "/usr/local/home/russel/mibi/Software/miniconda2/envs/drep/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/usr/local/home/russel/mibi/Software/miniconda2/envs/drep/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/usr/local/home/russel/mibi/Software/miniconda2/envs/drep/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/home/russel/mibi/Software/miniconda2/envs/drep/lib/python3.6/site-packages/drep/d_workflows.py", line 36, in dereplicate_wrapper
    drep.d_cluster.d_cluster_wrapper(wd, **kwargs)
  File "/usr/local/home/russel/mibi/Software/miniconda2/envs/drep/lib/python3.6/site-packages/drep/d_cluster.py", line 80, in d_cluster_wrapper
    data_folder, wd=workDirectory, **kwargs)
  File "/usr/local/home/russel/mibi/Software/miniconda2/envs/drep/lib/python3.6/site-packages/drep/d_cluster.py", line 208, in cluster_genomes
    logging.error("CRITICAL ERROR WITH PRIMARY CLUSTER {0}; SKIPPING".foramt(name))
AttributeError: 'str' object has no attribute 'foramt'

**Comment by MrOlm** [comment]
Hello,

This is a bug that's unique to version 2.5.1- upgrading to anything beyond that should fix this problem. Upgrade with `pip install drep --upgrade`.

Please let me know if this doesn't fix the problem

-Matt

**Comment by Russel88** [comment]
Great! Thanks for the fast reply

- Jakob
