### ISSUE TITLE
OSError issue

### ISSUE THREAD

**Issue by WJunHao** [MrOlm/drep#113]
hello. I installed the drep v3.2.0 by using miniconda3. python version is 3.6.0. When I ran `dRep dereplicate --ignoreGenomeQuality outout_test -g test/*.fasta`, step 1 and 2 were both good status, but some problems showed in step 3&4. Results as follows:
`..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
10 primary clusters made
Running secondary clustering
Running 10 ANImf comparisons- should take ~ 0.8 min
Step 4. Return output
***************************************************
    ..:: dRep dereplicate Step 3. Choose ::..
***************************************************
    
Loading work directory
Traceback (most recent call last):
  File "/home/wangjunhao/miniconda3/envs/drep/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/home/wangjunhao/miniconda3/envs/drep/lib/python3.6/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/wangjunhao/miniconda3/envs/drep/lib/python3.6/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/wangjunhao/miniconda3/envs/drep/lib/python3.6/site-packages/drep/d_workflows.py", line 45, in dereplicate_wrapper
    drep.d_choose.d_choose_wrapper(wd, **kwargs)
  File "/home/wangjunhao/miniconda3/envs/drep/lib/python3.6/site-packages/drep/d_choose.py", line 88, in d_choose_wrapper
    wd.store_special('dereplicated_genomes', derep_genomes)
  File "/home/wangjunhao/miniconda3/envs/drep/lib/python3.6/site-packages/drep/WorkDirectory.py", line 334, in store_special
    shutil.rmtree(output_folder)
  File "/home/wangjunhao/miniconda3/envs/drep/lib/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/wangjunhao/miniconda3/envs/drep/lib/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 26] Text file busy: '/home/wangjunhao/share/PY-gam-con/outout_test/dereplicated_genomes/'
`
But there is nothing in "dereplicated_genomes". So, what means "Text file busy", I am confusing for this problem.
Thank you for your attention.

**Comment by MrOlm** [comment]
Hello,

That's a really strange error that I haven't come across before. Please try and run it again in a new directory, and please add `-d` to the command to run in debug mode. If you hit the same error again, please send me the file `logger.log` in the `log` folder.

-Matt
