### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by zxgsy520** [MrOlm/drep#139]
```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Running checkM
0.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
  Final step: comparing between all groups
Traceback (most recent call last):
  File "/Work/pipeline/software/meta/drep/v3.0.0/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/drep/controller.py", line 99, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/drep/d_cluster/compare_utils.py", line 120, in all_vs_all_MASH
    return run_second_round_clustering(Bdb, genome_chunks, data_folder, **kwargs)
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/drep/d_cluster/compare_utils.py", line 222, in run_second_round_clustering
    Cdb = pd.concat(dbs)
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/Work/pipeline/software/meta/drep/v3.0.0/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```
What's wrong with this error？

**Comment by MrOlm** [comment]
Hello,

No genomes are passing the checkM filters you have set. You can each adjust the filters or remove them entirely.

Best,
Matt

**Comment by lucaz88** [comment]
Hi Matt,
I am trying to incorporate dRep into a snakemake workflow and it could happen that sometimes a sample do not generate good enough bins that pass the 1. Filter. Is there a way to do not get directly an error from dRep? e.g. that simply finishes and there will be no genomes in the dereplicated_genomes folder?

**Comment by MrOlm** [comment]
Hi @lucaz88 -

As of right now I don't believe there's a way to do this. I will add this feature to my "To Do" list, but it will probably take me a while to fix it. Apologizes. 

If you happen to know python and are able to submit a pull request I would be happy to review / accept it?

Best,
Matt

**Comment by chaoyanggu** [comment]
Hi Matt,
I met the same error, about 0.00% of genomes passed checkM filtering. My codes as followings,
 dRep   dereplicate  . /  -g  ./fa/*.fa   -pa  0.9    -sa 0.95  -nc 0.30   -cm larger   -p 10 
How can I adjust my filters  so that I can continue running.  And  my input *.fa were the assembled contigs  downloaded from NCBI, every fa file contains only one contig. 
Thank you.

**Comment by MrOlm** [comment]
Hi @chaoyanggu ,

You need every file to be a full genome. If fa file is a genome in one contig, that's fine.

You can either switch from `dereplicate` to `compare`, or you can add `--ignoreGenomeQuality` to your `dereplicate` command

-Matt
