### ISSUE TITLE
check_dependencies report fastANI ERROR, dRep process cannot complete

### ISSUE THREAD

**Issue by sleepvet** [MrOlm/drep#164]
The drep v3.4.0 is installed by conda.  Although I installed fastANI and tested it well, I found that fastANI was still reported errors after checking it with check_dependencies. I thought the error was OK, but unfortunately, the dRep program stopped when fastANI running.
 Also attach the log file.

[logger.log](https://github.com/MrOlm/drep/files/9692442/logger.log)

**Comment by MrOlm** [comment]
Hi @sleepvet -

fastANI needs to show up as working with the `check_dependencies` command for dRep to be able to use it.

When it shows up as not working, often a problem is that it's not accessible in the system path. For example, try and run `fastANI -h` immediately before the dRep command in the the same environment. That's essentially the same check dRep is doing when it runs `check_dependencies`

Best,
Matt

**Comment by sleepvet** [comment]
Dear Matt:
I am afraid it is not my case. when I run check_dependencies, the dRep reports:
mash.................................... all good        (location = /home/mzy/miniconda3/envs/drep/bin/mash)
nucmer.................................. all good        (location = /home/mzy/miniconda3/envs/drep/bin/nucmer)
checkm.................................. all good        (location = /home/mzy/miniconda3/envs/drep/bin/checkm)
ANIcalculator........................... all good        (location = /usr/bin/ANIcalculator)
prodigal................................ all good        (location = /home/mzy/miniconda3/envs/drep/bin/prodigal)
centrifuge.............................. !!! ERROR !!!   (location = None)
nsimscan................................ all good        (location = /usr/bin/nsimscan)
fastANI................................. !!! ERROR !!!   (location = /home/mzy/miniconda3/envs/drep/bin/fastANI)
clearly, fastANI is in the PATH. When I run fastANI -h, all looks good.

**Comment by sleepvet** [comment]
This is the error report when I run dRep
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
  Will split genomes into 2 groups for primary clustering
3024 primary clusters made
Running secondary clustering
Running 73333 fastANI comparisons- should take ~ 271.1 min
Traceback (most recent call last):
  File "/home/mzy/miniconda3/envs/drep/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_cluster/controller.py", line 35, in main
    self.run_secondary_clustering()
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_cluster/controller.py", line 140, in run_secondary_clustering
    Ndb, Cdb, c2ret = drep.d_cluster.compare_utils.secondary_clustering(self.Bdb, self.MCdb, algorithm, self.wd.get_dir('data'), wd=self.wd, **self.kwargs)
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_cluster/compare_utils.py", line 298, in secondary_clustering
    ndb = compare_genomes(bdb, algorithm, data_folder, **kwargs)
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_cluster/compare_utils.py", line 367, in compare_genomes
    df = drep.d_cluster.external.run_pairwise_fastANI(genome_list, working_data_folder, **kwargs)
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_cluster/external.py", line 93, in run_pairwise_fastANI
    exe_loc = drep.get_exe('fastANI')
  File "/home/mzy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/__init__.py", line 100, in get_exe
    raise ValueError("{0} isn't working- make sure its installed".format(name))
ValueError: fastANI isn't working- make sure its installed

**Comment by sleepvet** [comment]
I think this is a problem caused by conda. The problem solved when fastANI installed from source code.
