### ISSUE TITLE
Error running secondary clustering

### ISSUE THREAD

**Issue by erichy91** [MrOlm/drep#167]
Hi Matt,

I get the following error message when I run dRep. I first tried the program on a subset of genomes and it worked. Then I tried it on about 3000 genomes, and I get the same error message. Now I also get this error message when I retest the same subset of genomes. Do you have any idea what is going on?

Thank you!

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
87 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
100.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
87 primary clusters made
Running secondary clustering
Running 87 fastANI comparisons- should take ~ 0.1 min
Traceback (most recent call last):
  File "/opt/conda/envs/drep/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 35, in main
    self.run_secondary_clustering()
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 140, in run_secondary_clustering
    Ndb, Cdb, c2ret = drep.d_cluster.compare_utils.secondary_clustering(self.Bdb, self.MCdb, algorithm, self.wd.get_dir('data'), wd=self.wd, **self.kwargs)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/d_cluster/compare_utils.py", line 298, in secondary_clustering
    ndb = compare_genomes(bdb, algorithm, data_folder, **kwargs)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/d_cluster/compare_utils.py", line 367, in compare_genomes
    df = drep.d_cluster.external.run_pairwise_fastANI(genome_list, working_data_folder, **kwargs)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/d_cluster/external.py", line 106, in run_pairwise_fastANI
    fdb = load_fastani(out_base)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/drep/d_cluster/external.py", line 140, in load_fastani
    fdb = pd.read_csv(file, names=['reference', 'querry', 'ANI', 'j1', 'j2'], delim_whitespace=True)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/envs/drep/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/DATA1/MAGs/drep_res/data/fastANI_files/fastANI_out_gqxnaohwwg'
```

**Comment by erichy91** [comment]
Hi Matt,

Thanks for your quick reply. I solved the problem by running the command with -d. I realised that the default algorithm for secondary clustering was fastANI, and when I switched to ANImf, it worked. 

Thanks for your help,
Etienne
