### ISSUE TITLE
checkM table input

### ISSUE THREAD

**Issue by lhor** [MrOlm/drep#17]
When I try to use a checkM-generated table using the `--Chdb` option I get the following error:

`Will filter the genome list
100.00% of genomes passed length filtering
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2522, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Bin Id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_wf_operation(**vars(args))
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_wf_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_workflows.py", line 28, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_filter.py", line 65, in d_filter_wrapper
    validate_chdb(Chdb, bdb)
  File "/usr/local/lib/python3.6/site-packages/drep/d_filter.py", line 127, in validate_chdb
    if genome not in Chdb['Bin Id'].tolist():
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 3838, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2524, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: Bin Id``
If I compare the checkM file generated during a dRep run to the one I'm using with `--Chdb` option, they look the same (i.e., same number of columns, etc). Even If I use the .tsv file generated by dRep, I get the same error.

**Comment by MrOlm** [comment]
Hmm. Would you mind sending me a fraction the file that you're passing in with the "Chdb" option? The column headers and one row of data should be enough.

Also, thank you for being thoughtful in that way that you're asking these questions such that they're useful to others- I really appreciate it

Best,
-Matt

**Comment by lhor** [comment]
No problem! A few lines from the file:
`Bin Id	Marker lineage	# genomes	# markers	# marker sets	Completeness	Contamination	Strain heterogeneity	Genome size (bp)	# ambiguous bases	# scaffolds	# contigs	N50 (scaffolds)	N50 (contigs)	Mean scaffold length (bp)	Mean contig length (bp)	Longest scaffold (bp)	Longest contig (bp)	GC	GC std (scaffolds > 1kbp)	Coding density	Translation table	# predicted genes	0	1	2	3	4	5+
20100303_Bin_36_2-contigs	f__Flavobacteriaceae (UID2845)	53	548	298	92.70	0.67	100.00	1989845	0	120	120	29564	29564	16582	16582	168709	168709	31.4	1.84	93.93	11	1894	32	514	2	0	0	0`

**Comment by MrOlm** [comment]
OK- I think I see the problem. Could you try saving the file as a `.csv` instead of .tsv, and see if that works? That is, replace all of the tabs with commas. If you have excel or google sheets it should be able to do it for your pretty easily. 

Thanks,
-Matt

**Comment by lhor** [comment]
Perfect, it works now!
Thanks!
Coto

**Comment by lhor** [comment]
Actually, I just realized that after running it didn't work. Even though changing the format from tsv to csv fixed the initial error, when it reads the file at the end it doesn't seem to work (maybe is expecting a .tsv file?)
`***************************************************
    ..:: dRep Step 1. Filter ::..
***************************************************
    
Will filter the genome list
100.00% of genomes passed length filtering
63.83% of genomes passed checkM filtering
***************************************************
    ..:: dRep Step 2. Cluster ::..
***************************************************
    
Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
16 primary clusters made
Step 3. Perform secondary clustering
Running 1686 ANImf comparisons- should take ~ 281.0 min
Step 4. Return output
***************************************************
    ..:: dRep Step 3. Choose ::..
***************************************************
    
Loading work directory
Chdb (CheckM information) not found- running CheckM now
Running prodigal
!!! checkM failed !!!
If using pyenv, make sure both python2 and python3 are available (for example: pyenv global 3.5.1 2.7.9)`

**Comment by MrOlm** [comment]
OK, I see the problem. There are two solutions:

1) If you name your checkM file `Chdb.csv`, and put it in the workDirectory folder: `data_tables`, dRep will recognize what it is and load it. You could then just run the command `dRep choose <workDirectory>`, and will pick the best genome from each cluster and population the folder `derplicated_genomes`. You could then run `dRep analyze <workDirectory> -pl a` to make the plots in the `figures` folder. These steps will both run very quickly, so you won't need to re-run any of the previous filtering or clustering steps.

**Comment by MrOlm** [comment]
FYI, version 2.0 has been pushed to master with better ways of handling external checkM results. See http://drep.readthedocs.io/en/master/advanced_use.html#using-external-genome-quality-information for more information
