### ISSUE TITLE
0.00% of genomes passed checkM filtering

### ISSUE THREAD

**Issue by steffie11** [MrOlm/drep#176]
Dear developers,

I am trying to run drep of these three plant genomes:
_Pinus lambertiana_ (GCA_001447015.2)
_Picea glauca_ (GCA_000966675.3)
_Pinus taeda_ (GCA_000404065.3)

I place these three genomes in a folder called "`large_genome`" and run `dRep dereplicate outout_directory -g large_genome/*.fna`
Then I receive the following the errors:
`***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Past prodigal runs found- will not re-run
Running checkM
0.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
  Final step: comparing between all groups
Traceback (most recent call last):
  File "/home/ollie/shuang/miniconda3/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/drep/controller.py", line 99, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/drep/d_cluster/compare_utils.py", line 120, in all_vs_all_MASH
    return run_second_round_clustering(Bdb, genome_chunks, data_folder, **kwargs)
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/drep/d_cluster/compare_utils.py", line 222, in run_second_round_clustering
    Cdb = pd.concat(dbs)
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 347, in concat
    op = _Concatenator(
  File "/home/ollie/shuang/miniconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
srun: error: fat-0002: task 0: Exited with exit code 1
srun: Terminating job step 20791164.0
`

Could you pls help with that? Thanks a lot.

Cheers,
Huang

**Comment by MrOlm** [comment]
Hi Huang,

Apologies for the long response time! I must have missed this email when it came by.

The issue is that your genomes are not passing checkM filtering, which you probably don't want to run anyways since it only works on bacteria. You can skip this filtering step by adding the argument `--ignoreGenomeQuality` to your comment.

Best,
Matt
