### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by marcellobeltrami** [MrOlm/drep#177]
Hello Matt. I am getting this while comparing my genomes. I am not sure if its my inability or there is something wrong with the software. I thought to flag it just in case. Thank You!

***************************************************
    ..:: dRep compare Step 1. Cluster ::..
***************************************************

Running primary clustering
Running pair-wise MASH clustering
17 primary clusters made
Running secondary clustering
Running 616 fastANI comparisons- should take ~ 14.3 min
Traceback (most recent call last):
  File "/home/marcello/.local/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/controller.py", line 102, in parseArguments
    self.compare_operation(**vars(args))
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/controller.py", line 53, in compare_operation
    drep.d_workflows.compare_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/d_workflows.py", line 97, in compare_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 35, in main
    self.run_secondary_clustering()
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 140, in run_secondary_clustering
    Ndb, Cdb, c2ret = drep.d_cluster.compare_utils.secondary_clustering(self.Bdb, self.MCdb, algorithm, self.wd.get_dir('data'), wd=self.wd, **self.kwargs)
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/d_cluster/compare_utils.py", line 298, in secondary_clustering
    ndb = compare_genomes(bdb, algorithm, data_folder, **kwargs)
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/d_cluster/compare_utils.py", line 367, in compare_genomes
    df = drep.d_cluster.external.run_pairwise_fastANI(genome_list, working_data_folder, **kwargs)
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/d_cluster/external.py", line 106, in run_pairwise_fastANI
    fdb = load_fastani(out_base)
  File "/home/marcello/.local/lib/python3.10/site-packages/drep/d_cluster/external.py", line 140, in load_fastani
    fdb = pd.read_csv(file, names=['reference', 'querry', 'ANI', 'j1', 'j2'], delim_whitespace=True)
  File "/home/marcello/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/marcello/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/marcello/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/marcello/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
  File "/home/marcello/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/marcello/.local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 9 fields in line 2, saw 10

**Comment by MrOlm** [comment]
Hi @marcellobeltrami -

Interesting. Can you confirm that `dRep check_dependencies` show that fastANI is working for you? Also do any of your genome's names happen to have spaces in them?

-Matt

**Comment by marcellobeltrami** [comment]
Dear Matt, 
I corrected file names and dependencies and it worked!! Thank you for your help :)
