### ISSUE TITLE
Running partial CheckM stats causes fail from strain heterogeneity values

### ISSUE THREAD

**Issue by tanaes** [MrOlm/drep#180]
Discovered a subtle bug from PR #179 -- sorry!

The issue is that the input genomeInfo only checks for completeness and contamination, but when running CheckM internally, also adds heterogeneity values. This yields `nan` entries in genome rows with previously-computed CheckM values, which causes a list index out of range error when it ultimately goes to look up a score for that row:

```
***************************************************
    ..:: dRep dereplicate Step 3. Choose ::..
***************************************************
    
Loading work directory
Calculating centrality using Mash
Traceback (most recent call last):
  File "/home/jgsanders/miniconda3/envs/drep_test/bin/dRep", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/jgsanders/git_sw/drep/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/home/jgsanders/git_sw/drep/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/jgsanders/git_sw/drep/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/jgsanders/git_sw/drep/drep/d_workflows.py", line 45, in dereplicate_wrapper
    drep.d_choose.d_choose_wrapper(wd, **kwargs)
  File "/home/jgsanders/git_sw/drep/drep/d_choose.py", line 78, in d_choose_wrapper
    Sdb, Wdb = choose_winners(Cdb, Gdb, **kwargs)
  File "/home/jgsanders/git_sw/drep/drep/d_choose.py", line 117, in choose_winners
    Wdb = pick_winners(Sdb,Cdb)
  File "/home/jgsanders/git_sw/drep/drep/d_choose.py", line 179, in pick_winners
    genome = d['genome'][d['score'] == score].tolist()[0]
IndexError: list index out of range
```

I can solve this locally by testing for `nan` value within the `score_row` method:

```python
    if 'strain_heterogeneity' in row:
        if pd.isnull(row['strain_heterogeneity'].tolist()[0]):
            strh = 0
        else:
            strh = float(row['strain_heterogeneity'].tolist()[0])
    else:
        strh = 0
```

But not sure what the safest way to address this problem is. Perhaps testing for `nan` values in that column and setting `strain_heterogeneity_weight` to 0, with a warning, if it finds them?

Let me know your favored solution and I can implement in a new PR.

**Comment by MrOlm** [comment]
Hi @tanaes -

Thank you again for finding and reporting this bug! The solution you proposed sounds great to me! Happy to include the changes you made to the `score_row` method, or any other solution you come up with.

Thanks again!
-Matt
