### ISSUE TITLE
ValueError: 'label' must be of length 'x'

### ISSUE THREAD

**Issue by lhor** [MrOlm/drep#19]
Hi! I'm running the 2.0 version and at the end of the analysis, I get the error below. I'm not sure what is going on, but please let me know if you need more info about the run.
Thanks!
Coto

***************************************************
    ..:: dRep dereplicate Step 6. Analyze ::..
***************************************************
    
making plots 1, 2, 3, 4, 5, 6
Plotting primary dendrogram
Plotting secondary dendrograms
Plotting MDS plot
Plotting scatterplots
Plotting bin scorring plot
Plotting winning genomes plot...
Traceback (most recent call last):
  File "/usr/local/bin/drep", line 26, in <module>
    controller.parseArguments(args)
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_workflows.py", line 68, in dereplicate_wrapper
    drep.d_analyze.d_analyze_wrapper(wd, plots = 'a', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_analyze.py", line 78, in d_analyze_wrapper
    plot_winners_from_wd(wd, plot_dir, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_analyze.py", line 345, in plot_winners_from_wd
    plot_winners(Wdb, Gdb, Wndb, Wmdb, Widb, plot_dir = plot_dir, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_analyze.py", line 734, in plot_winners
    _make_piechart(labels,sizes)
  File "/usr/local/lib/python3.6/site-packages/drep/d_analyze.py", line 878, in _make_piechart
    shadow = True)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3219, in pie
    frame=frame, rotatelabels=rotatelabels, data=data)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1710, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 2635, in pie
    raise ValueError("'label' must be of length 'x'")
ValueError: 'label' must be of length 'x'

**Comment by MrOlm** [comment]
Hi Coto,

It looks like it's a silly error having to do with making a pie chart in one of the figures. I will debug and let you know when finished, but just FYI it shouldn't effect anything else about the run besides that one figure.

-Matt

**Comment by MrOlm** [comment]
This issue has been somewhat addressed in version 2.0.2. I still can't figure out why making that particular figure is failing sometimes, but I've changed it so that it crashes more gracefully and makes as many plots as it can (even if it fails on one plot in particular).
-Matt
