### ISSUE TITLE
Error MASH clustering 

### ISSUE THREAD

**Issue by stephane-wang** [MrOlm/drep#191]
Hi, I just started using drep recently and I was able to run it once on about 6300 genomes.

However I am encountering an error right now and I don't understand how i can resolve it. I used the same command as the first time except that I added more processors but nothing else should have changed.

The first time I ran dereplicate I gave it a file with the absolute path to the genomes. 
This time I first copied all genomes in a single directory and ran **`dRep dereplicate work_dir -d -g path/to/directory/*fna -pa 0.9 -sa 0.95 -nc 0.30 -cm larger -p 20`** but after it stopped at MASH clustering I instead gave it a file with the absolute path just like my first time to see if anything changed but the it still stopped at this step.

**
dRep dereplicate 4.drep_7283_test2/ -d -g bin_7283 --genomeInfo 4.drep_7283_test2/genomeInfo.csv -pa 0.9 -sa 0.95 -nc 0.30 -cm larger -p 20
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************

Will filter the genome list
Loading genomes from a list
7,283 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
99.37% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************

Running primary clustering
Running pair-wise MASH clustering
  Will split genomes into 2 groups for primary clustering
Traceback (most recent call last):
  File "/home/swang/.conda/envs/dRep/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/home/swang/.conda/envs/dRep/lib/python3.10/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/swang/.conda/envs/dRep/lib/python3.10/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/swang/.conda/envs/dRep/lib/python3.10/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/home/swang/.conda/envs/dRep/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/home/swang/.conda/envs/dRep/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/home/swang/.conda/envs/dRep/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
  File "/home/swang/.conda/envs/dRep/lib/python3.10/site-packages/drep/d_cluster/compare_utils.py", line 115, in all_vs_all_MASH
    Cdb, cluster_ret = cluster_mash_database(Mdb, **kwargs)
  File "/home/swang/.conda/envs/dRep/lib/python3.10/site-packages/drep/d_cluster/compare_utils.py", line 279, in cluster_mash_database
    linkage_db = db.pivot("genome1","genome2","dist")
TypeError: DataFrame.pivot() takes 1 positional argument but 4 were given
**

Above is the command I used and the error I ran into.
Thanks for your help !

PS: I just realised issue #189 had the same problem. I'll try downgrading as suggested there

**Comment by MrOlm** [comment]
Yes exactly this is a problem with the newest version of pandas- an upcoming dRep update should fix, but for now downgrading pandas is the way to go
