### ISSUE TITLE
Error when I run dRep

### ISSUE THREAD

**Issue by yuanpingdu** [MrOlm/drep#197]
When I run dRep dereplicate Step 2. Cluster, and there is an error:

Comparing 88,329 genomes
Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/usr/local/lib/python3.6/dist-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/compare_utils.py", line 120, in all_vs_all_MASH
    return run_second_round_clustering(Bdb, genome_chunks, data_folder, verbose=True, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/compare_utils.py", line 246, in run_second_round_clustering
    Cdb2, cluster_ret = cluster_mash_database(mdb, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/compare_utils.py", line 279, in cluster_mash_database
    linkage_db = db.pivot("genome1","genome2","dist")
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 6678, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/pivot.py", line 477, in pivot
    return indexed.unstack(columns)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 3902, in unstack
    return unstack(self, level, fill_value)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/reshape.py", line 425, in unstack
    obj.index, level=level, constructor=obj._constructor_expanddim,
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/reshape.py", line 118, in __init__
    raise ValueError("Unstacked DataFrame is too big, causing int32 overflow")
ValueError: Unstacked DataFrame is too big, causing int32 overflow
tar: Removing leading `/' from member names

How should we do to slove it?

**Comment by MrOlm** [comment]
Hi @yuanpingdu - can you confirm that you are running the latest version of dRep? I think this is a bug I fixed in a previous version

**Comment by MrOlm** [comment]
Hi @yuanpingdu - sorry that was bad advice. Please upgrade pandas to at least version 1.4, or downgrade pandas to version 0.21.

Best,
Matt

**Comment by yuanpingdu** [comment]
> Hi @yuanpingdu - sorry that was bad advice. Please upgrade pandas to at least version 1.4, or downgrade pandas to version 0.21.
> 
> Best, Matt

Hi Matt
     I  used v3.2.2 of dRep, when I downgrade pandas to version 0.21. There was another error:
Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/usr/local/lib/python3.6/dist-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/compare_utils.py", line 110, in all_vs_all_MASH
    genome_chunks = run_mash_on_genome_chunks(genome_chunks, mash_exe, sketch_folder, MASH_folder, logdir,  **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/compare_utils.py", line 198, in run_mash_on_genome_chunks
    GC.load_mash_table()
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/compare_utils.py", line 58, in load_mash_table
    Mdb = drep.d_cluster.utils.parse_mash_table(self.dist_file)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/utils.py", line 135, in parse_mash_table
    Mdb = pd.read_csv(location, names=iniCols, usecols=uCols, dtype=dTypes, sep='\t')
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 705, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 451, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1065, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1828, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 894, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 944, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 2218, in pandas._libs.parsers._concatenate_chunks
  File "/usr/local/lib/python3.6/dist-packages/numpy-1.19.4-py3.6-linux-x86_64.egg/numpy/core/numerictypes.py", line 621, in find_common_type
    array_types = [dtype(x) for x in array_types]
  File "/usr/local/lib/python3.6/dist-packages/numpy-1.19.4-py3.6-linux-x86_64.egg/numpy/core/numerictypes.py", line 621, in <listcomp>
    array_types = [dtype(x) for x in array_types]
TypeError: Cannot interpret 'CategoricalDtype(categories=['/data/data/BL-unmapped_bin_256.fa',
                  '/data/data/Boar-s10_bin_46.fa',
                  '/data/data/Boar-s19_bin_12.fa',
                  '/data/data/C4974_bin_52.fa', '/data/data/C4975_bin_41.fa',
                  '/data/data/F4962_bin_51.fa', '/data/data/F4975_bin_22.fa',
                  '/data/data/F5115_bin_75.fa', '/data/data/F5123_bin_27.fa',
                  '/data/data/F5184_bin_25.fa', '/data/data/F5205_bin_10.fa',
                  '/data/data/F5210_bin_55.fa', '/data/data/F5218_bin_16.fa',
                  '/data/data/F5347_bin_35.fa', '/data/data/F5374_bin_13.fa',
                  '/data/data/F5412_bin_52.fa', '/data/data/F5520_bin_44.fa',
                  '/data/data/F5606_bin_18.fa',
                  '/data/data/GCF_000007885.1_ASM788v1_genomic.fa',
                  '/data/data/GCF_000016685.1_ASM1668v1_genomic.fa',
                  '/data/data/GCF_000016985.1_ASM1698v1_genomic.fa',
                  '/data/data/GCF_000024325.1_ASM2432v1_genomic.fa',
                  '/data/data/GCF_000025825.1_ASM2582v1_genomic.fa',
                  '/data/data/GCF_000154185.1_ASM15418v1_genomic.fa',
                  '/data/data/GCF_000157535.1_ASM15753v1_genomic.fa',
                  '/data/data/GCF_000161335.1_ASM16133v1_genomic.fa',
                  '/data/data/GCF_000168255.1_ASM16825v1_genomic.fa'],
                 ordered=False)' as a data type
tar: Removing leading `/' from member names

**Comment by MrOlm** [comment]
Hi @yuanpingdu - this is a strange error that I've never encountered before. Can you confirm that you're running dRep from scratch, not the same directory as had been run before? Also could you please attach the log file?

Thanks,
Matt

**Comment by yuanpingdu** [comment]
@MrOlm The output  directory  is the same as before，but I have delete all files of the directory and it‘s a empty directory when I run。
All contents of the log file   is：

***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************

Will filter the genome list
Loading genomes from a list
402,355 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
99.43% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************

Running primary clustering
Running pair-wise MASH clustering
  Will split genomes into 81 groups for primary clustering
  Comparing group 1 of 81
  Comparing group 2 of 81
  Comparing group 3 of 81
  Comparing group 4 of 81
  Comparing group 5 of 81
  Comparing group 6 of 81
  Comparing group 7 of 81
  Comparing group 8 of 81
  Comparing group 9 of 81
  Comparing group 10 of 81
  Comparing group 11 of 81
  Comparing group 12 of 81
  Comparing group 13 of 81
  Comparing group 14 of 81
  Comparing group 15 of 81
  Comparing group 16 of 81
  Comparing group 17 of 81
  Comparing group 18 of 81
  Comparing group 19 of 81
  Comparing group 20 of 81
  Comparing group 21 of 81
  Comparing group 22 of 81
  Comparing group 23 of 81
  Comparing group 24 of 81
  Comparing group 25 of 81
  Comparing group 26 of 81
  Comparing group 27 of 81
  Comparing group 28 of 81
  Comparing group 29 of 81
  Comparing group 30 of 81
  Comparing group 31 of 81
  Comparing group 32 of 81
  Comparing group 33 of 81
  Comparing group 34 of 81
  Comparing group 35 of 81
  Comparing group 36 of 81
  Comparing group 37 of 81
  Comparing group 38 of 81
  Comparing group 39 of 81
  Comparing group 40 of 81
  Comparing group 41 of 81
  Comparing group 42 of 81
  Comparing group 43 of 81
  Comparing group 44 of 81
  Comparing group 45 of 81
  Comparing group 46 of 81
  Comparing group 47 of 81
  Comparing group 48 of 81
  Comparing group 49 of 81
  Comparing group 50 of 81
  Comparing group 51 of 81
  Comparing group 52 of 81
  Comparing group 53 of 81
  Comparing group 54 of 81
  Comparing group 55 of 81
  Comparing group 56 of 81
  Comparing group 57 of 81
  Comparing group 58 of 81
  Comparing group 59 of 81
  Comparing group 60 of 81
  Comparing group 61 of 81
  Comparing group 62 of 81
  Comparing group 63 of 81
  Comparing group 64 of 81
  Comparing group 65 of 81
  Comparing group 66 of 81
  Comparing group 67 of 81
  Comparing group 68 of 81
  Comparing group 69 of 81
  Comparing group 70 of 81
  Comparing group 71 of 81
  Comparing group 72 of 81
  Comparing group 73 of 81
  Comparing group 74 of 81
  Comparing group 75 of 81
  Comparing group 76 of 81
  Comparing group 77 of 81
  Comparing group 78 of 81
  Comparing group 79 of 81
  Comparing group 80 of 81
  Comparing group 81 of 81
Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/usr/local/lib/python3.6/dist-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/compare_utils.py", line 110, in all_vs_all_MASH
    genome_chunks = run_mash_on_genome_chunks(genome_chunks, mash_exe, sketch_folder, MASH_folder, logdir,  **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/compare_utils.py", line 198, in run_mash_on_genome_chunks
    GC.load_mash_table()
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/compare_utils.py", line 58, in load_mash_table
    Mdb = drep.d_cluster.utils.parse_mash_table(self.dist_file)
  File "/usr/local/lib/python3.6/dist-packages/drep/d_cluster/utils.py", line 135, in parse_mash_table
    Mdb = pd.read_csv(location, names=iniCols, usecols=uCols, dtype=dTypes, sep='\t')
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 705, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 451, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1065, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1828, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 894, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 944, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 2218, in pandas._libs.parsers._concatenate_chunks
  File "/usr/local/lib/python3.6/dist-packages/numpy-1.19.4-py3.6-linux-x86_64.egg/numpy/core/numerictypes.py", line 621, in find_common_type
    array_types = [dtype(x) for x in array_types]
  File "/usr/local/lib/python3.6/dist-packages/numpy-1.19.4-py3.6-linux-x86_64.egg/numpy/core/numerictypes.py", line 621, in <listcomp>
    array_types = [dtype(x) for x in array_types]
TypeError: Cannot interpret 'CategoricalDtype(categories=['/data/data/BL-unmapped_bin_256.fa',
                  '/data/data/Boar-s10_bin_46.fa',
                  '/data/data/Boar-s19_bin_12.fa',
                  '/data/data/C4974_bin_52.fa', '/data/data/C4975_bin_41.fa',
                  '/data/data/F4962_bin_51.fa', '/data/data/F4975_bin_22.fa',
                  '/data/data/F5115_bin_75.fa', '/data/data/F5123_bin_27.fa',
                  '/data/data/F5184_bin_25.fa', '/data/data/F5205_bin_10.fa',
                  '/data/data/F5210_bin_55.fa', '/data/data/F5218_bin_16.fa',
                  '/data/data/F5347_bin_35.fa', '/data/data/F5374_bin_13.fa',
                  '/data/data/F5412_bin_52.fa', '/data/data/F5520_bin_44.fa',
                  '/data/data/F5606_bin_18.fa',
                  '/data/data/GCF_000007885.1_ASM788v1_genomic.fa',
                  '/data/data/GCF_000016685.1_ASM1668v1_genomic.fa',
                  '/data/data/GCF_000016985.1_ASM1698v1_genomic.fa',
                  '/data/data/GCF_000024325.1_ASM2432v1_genomic.fa',
                  '/data/data/GCF_000025825.1_ASM2582v1_genomic.fa',
                  '/data/data/GCF_000154185.1_ASM15418v1_genomic.fa',
                  '/data/data/GCF_000157535.1_ASM15753v1_genomic.fa',
                  '/data/data/GCF_000161335.1_ASM16133v1_genomic.fa',
                  '/data/data/GCF_000168255.1_ASM16825v1_genomic.fa'],
                 ordered=False)' as a data type
tar: Removing leading `/' from member names

Done. Total elapsed time : 75985s

**Comment by MrOlm** [comment]
I'm sorry but this is just such a bizarre error that I've never seen before. My only thoughts are to 1) update python to a newer version; at least 3.7 and up to 3.10, and 2) after updating python update numpy and pandas to their newest versions. Since this error doesn't happen on other peoples machines (including mine) it must be a dependency thing.

Below is a list of the package versions I have on my machine, with python version 3.10, in which this error does not happen

```
$ pip list
Package         Version   Location
--------------- --------- ----------------------------
biopython       1.81
certifi         2022.12.7
checkm-genome   1.2.2
contourpy       1.0.7
cycler          0.11.0
Cython          0.29.34
DendroPy        4.5.2
drep            3.4.3     /Users/mattolm/Programs/drep
exceptiongroup  1.1.1
fonttools       4.39.3
iniconfig       2.0.0
joblib          1.2.0
kiwisolver      1.4.4
matplotlib      3.7.1
numpy           1.24.2
packaging       23.1
pandas          2.0.0
Pillow          9.5.0
pip             21.2.4
pluggy          1.0.0
pyparsing       3.0.9
pysam           0.21.0
pytest          7.3.1
python-dateutil 2.8.2
pytz            2023.3
scikit-learn    1.2.2
scipy           1.10.1
seaborn         0.12.2
setuptools      61.2.0
six             1.16.0
threadpoolctl   3.1.0
tomli           2.0.1
tqdm            4.65.0
tzdata          2023.3
wheel           0.37.1
```

Best,
Matt
