### ISSUE TITLE
checkM Error

### ISSUE THREAD

**Issue by SevanEsaian** [MrOlm/drep#201]
Hi Matt, 
I am trying to get dRep to run on 2 bins; however, checkM keeps giving me an error. When I run `dRep check_dependencies` , the output is: 
![Screenshot 2023-07-11 at 1 24 46 PM](https://github.com/MrOlm/drep/assets/62720396/1050adcf-36c3-401b-9b95-cbca9782ccb4)
After seeing that `checkm` is "all good", I ran the following command: `dRep dereplicate Actinobacteriota_drep_Test -g /home/sevan/TestBins_Coassembly/*.fasta -d ` 
I am attaching the output from `-d `to this issue. 
[Actinobacteriota_drep_Test.zip](https://github.com/MrOlm/drep/files/12021279/Actinobacteriota_drep_Test.zip)
Can you please take a look at the zip folder I have attached and see if there is a way to resolve this issue? Thanks so much for your time and help.

**Comment by MrOlm** [comment]
Hi @SevanEsaian - thanks for the detailed information. In the file `2023-07-11_13.27.21.585632.STDERR` you can see the error checkM is throwing:

```    Finished processing 0 of 2 (0.00%) bins.
Process Process-2:
Traceback (most recent call last):
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/site-packages/checkm/markerGeneFinder.py", line 130, in _processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/sevan/.checkm/hmms/phylo.hmm'
Process Process-3:
Traceback (most recent call last):
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/site-packages/checkm/markerGeneFinder.py", line 130, in _processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sevan/miniconda3/envs/drep/lib/python3.11/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/sevan/.checkm/hmms/phylo.hmm'

    Finished processing 0 of 2 (0.00%) bins.
    Finished processing 1 of 2 (50.00%) bins.
    Finished processing 2 of 2 (100.00%) bins.
```

CheckM has a setup step you have to do after installation, telling it where the checkM files are and things like that. It seems like that's the heart of the problem.

If fixing this is an issue, you can always run checkM external to dRep and provide the results to dRep.

Best,
Matt

**Comment by SevanEsaian** [comment]
Hi Matt, 
Thanks so much for your prompt reply and clarification. While I'm working on troubleshooting the checkM installation issue, I wanted to ask you a quick question. If I wanted to run checkM externally and provide the results to dRep, how would I set that up as a command on dRep? Thanks again.

**Comment by SevanEsaian** [comment]
Thanks so much! I will try this first and if everything runs correctly, I will mark this issue resolved.

**Comment by SevanEsaian** [comment]
Hi Matt - you were correct. I had an incomplete installation. Now it is running. I will close this thread. Thanks again for your help.
