### ISSUE TITLE
UnboundLocalError: local variable 'c2ret' referenced before assignment

### ISSUE THREAD

**Issue by schmidoletti** [MrOlm/drep#209]
Hi,

I'm running dRep on some MAGs. To accommodate the large number of assemblies, I've followed the suggestions given in issue [#174](https://github.com/MrOlm/drep/issues/174). Here are the parameters I am using:

```
dRep \
    dereplicate \
        --processors 100 \
        --genomes /drep/input/metagenomes_input.txt \
        --genomeInfo /drep/input/metagenome_info.csv \
        --debug \
        --completeness 50 \
        --contamination 10 \
        --multiround_primary_clustering \
        --greedy_secondary_clustering \
        --primary_chunksize 10000 \
        --S_algorithm fastANI \
        --P_ani 0.90 \
        --S_ani 0.93 \
        --cov_thresh 0.5 \
        /drep/output_95_metagenomes_firstround_v2;
```

However, the process froze up during the MASH clustering stage. Given that I had used the `--debug` flag, I stopped the process and started again (using fewer threads), hoping it would continue from where I left off. However, I came up against the following error:

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
NOTE: Clustering already exists! This will not be filtered! Be sure you know what you're doing
Will filter Bdb
460,442 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
100.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Nevermind! Loading cached primary clustering
2. Primary clustering cache loaded
3993 primary clusters made
Running secondary clustering
3. Loading cached secondary clustering
3. Secondary clustering cache loaded
Traceback (most recent call last):
  File "/code/conda_envs/metachip/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 35, in main
    self.run_secondary_clustering()
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 146, in run_secondary_clustering
    self.wd.store_special('secondary_linkages', c2ret)
UnboundLocalError: local variable 'c2ret' referenced before assignment

```
Is there a solution so that I can continue from where I left off the first time?

Many thanks!

**Comment by MrOlm** [comment]
Hi @schmidoletti,

Thanks for brining this to my attention; this is caused by a silly bug in the program. Minutes ago I pushed a new dRep version (3.4.4) to GitHub and PyPi that should fix this issue.

Apologies and let me know if this doesn't fix your problem

Matt

**Comment by schmidoletti** [comment]
Thanks Matt!

I've just run it again after updating to 3.4.4 and now I'm getting a different, yet similar error:

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
NOTE: Clustering already exists! This will not be filtered! Be sure you know what you're doing
Will filter Bdb
460,442 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
100.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Nevermind! Loading cached primary clustering
2. Primary clustering cache loaded
3993 primary clusters made
Running secondary clustering
3. Loading cached secondary clustering
3. Secondary clustering cache loaded
Step 4. Return output
Traceback (most recent call last):
  File "/code/conda_envs/metachip/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 35, in main
    self.run_secondary_clustering()
  File "/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 156, in run_secondary_clustering
    self.Cdb = Cdb
UnboundLocalError: local variable 'Cdb' referenced before assignment
```

**Comment by MrOlm** [comment]
Hi @schmidoletti -

OK- I pushed v3.4.5 that should fix this issue as well. This whole "cache"ing system is very hacked together and not officially supported by dRep, but I think this last update should fix the problem you're hitting.

Best,
Matt

**Comment by schmidoletti** [comment]
Thanks again!

> This whole "cache"ing system is very hacked together and not officially supported by dRep

But it's such a valuable time-saver!! Especially when working with a large number of MAGs..

So I updated to v3.4.5 and continued. This time it seemed to work, but I did get a new error:

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
NOTE: Clustering already exists! This will not be filtered! Be sure you know what you're doing
Will filter Bdb
460,442 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
100.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Nevermind! Loading cached primary clustering
2. Primary clustering cache loaded
3993 primary clusters made
Running secondary clustering
3. Loading cached secondary clustering
!!! 0 lines from Ndb failed!
3. Secondary clustering cache loaded
Step 4. Return output
***************************************************
    ..:: dRep dereplicate Step 3. Choose ::..
***************************************************
    
Loading work directory
Calculating centrality using Mash
  Will split genomes into 3 groups for primary clustering
  Comparing group 1 of 3
  Comparing group 2 of 3
  Comparing group 3 of 3
  Final step: comparing between all groups
Comparing 3 genomes
  Will split genomes into 2 groups for primary clustering
  Comparing group 1 of 2
  Comparing group 2 of 2
  Final step: comparing between all groups
Comparing 2 genomes
  Will split genomes into 2 groups for primary clustering
  Comparing group 1 of 2
  Comparing group 2 of 2
  Final step: comparing between all groups
Comparing 2 genomes
  Will split genomes into 2 groups for primary clustering
  Comparing group 1 of 2
  Comparing group 2 of 2
  Final step: comparing between all groups
Comparing 2 genomes
  Will split genomes into 2 groups for primary clustering
  Comparing group 1 of 2
  Comparing group 2 of 2
  Final step: comparing between all groups
Comparing 2 genomes
  Will split genomes into 2 groups for primary clustering
  Comparing group 1 of 2
  Comparing group 2 of 2
  Final step: comparing between all groups
Comparing 2 genomes
  Will split genomes into 2 groups for primary clustering
  Comparing group 1 of 2
  Comparing group 2 of 2
  Final step: comparing between all groups
Comparing 2 genomes
  Will split genomes into 2 groups for primary clustering
  Comparing group 1 of 2
  Comparing group 2 of 2
  Final step: comparing between all groups
Comparing 2 genomes
  Will split genomes into 2 groups for primary clustering
  Comparing group 1 of 2
  Comparing group 2 of 2
  Final step: comparing between all groups
Comparing 2 genomes
  Will split genomes into 2 groups for primary clustering
  Comparing group 1 of 2
  Comparing group 2 of 2
  Final step: comparing between all groups
Comparing 2 genomes
  Will split genomes into 3 groups for primary clustering
  Comparing group 1 of 3
  Comparing group 2 of 3
  Comparing group 3 of 3
  Final step: comparing between all groups
Comparing 3 genomes
Traceback (most recent call last):
  File "/tmp/global2/jmarsh/code/conda_envs/metachip/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/tmp/global2/jmarsh/code/conda_envs/metachip/lib/python3.10/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/tmp/global2/jmarsh/code/conda_envs/metachip/lib/python3.10/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/tmp/global2/jmarsh/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_workflows.py", line 45, in dereplicate_wrapper
    drep.d_choose.d_choose_wrapper(wd, **kwargs)
  File "/tmp/global2/jmarsh/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_choose.py", line 72, in d_choose_wrapper
    Gdb = add_centrality(wd, Gdb, **kwargs)
  File "/tmp/global2/jmarsh/code/conda_envs/metachip/lib/python3.10/site-packages/drep/d_choose.py", line 334, in add_centrality
    assert len(ndb) == (mlen * mlen) - mlen
AssertionError
```

So I ran it again using `--centrality_weight 0` and everything worked. Thanks for sorting that out. But I'm wondering if `--centrality_weight 0` is going to affect the scoring criteria?
