### ISSUE TITLE
Error bonus step

### ISSUE THREAD

**Issue by palomo11** [MrOlm/drep#21]
Hi,

I have run dereplication. Genomes have been properly dereplicated but it has been an error during the bonus step:

This is the command I have run:

dRep dereplicate -p 28 output_dir -g genomes/*.fasta --genomeInfo genomeinfo.csv --run_tax --cent_index /home/name/scripts/centrifuge_database/

In /home/name/scripts/centrifuge_database/  it can be found these files and folders:
abv.1.cf  abv.2.cf  abv.3.cf  input-sequences.fna  library  seqid2taxid.map  taxonomy

is that the correct path to include in --cent_index?

***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
99.08% of genomes passed length filtering
42.52% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Clustering Step 1. Parse Arguments
Clustering Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
100 primary clusters made
Step 3. Perform secondary clustering
Running 11390 ANImf comparisons- should take ~ 203.4 min
Step 4. Return output
***************************************************
    ..:: dRep dereplicate Step 3. Choose ::..
***************************************************
    
Loading work directory
***************************************************
    ..:: dRep dereplicate Step 4. Bonus ::..
***************************************************
    
Loading work directory
Running tax
Running Centrifuge
Traceback (most recent call last):
  File "/services/tools/anaconda3/4.0.0/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_workflows.py", line 52, in dereplicate_wrapper
    drep.d_bonus.d_bonus_wrapper(wd, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 26, in d_bonus_wrapper
    run_taxonomy(wd,**kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 45, in run_taxonomy
    Tdb, Bdb = parse_taxonomy(Bdb, cent_dir, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 62, in parse_taxonomy
    Tdb = parse_centrifuge_percent(Bdb, cent_dir, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 200, in parse_centrifuge_percent
    "{0}{1}_report.tsv".format(cent_dir,genome))
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 340, in parse_raw_centrifuge
    tax = pd.read_table(report)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/home/output_dir/data/centrifuge/102_Con1500.fasta_report.tsv' does not exist

In the data folder both prodigal and centrifuge folders are empty:

83 Jan 12 14:44 MASH_files
53130 Jan 12 15:43 ANImf_files
5014 Jan 12 15:43 Clustering_files
     0 Jan 12 15:45 prodigal
     0 Jan 12 15:45 centrifuge

And I have also seen this error:

Warning: Could not open read file "/home/output_dir/data/centrifuge/103_Con1500.fasta.fna" for reading; skipping...
Error: No input read files were valid
(ERR): centrifuge-class exited with value 1

Thank you very much in advance.

**Comment by MrOlm** [comment]
Hello,

So a couple of things-

First, for the centrifuge database that you created, the location you should enter is:

`/home/name/scripts/centrifuge_database/abv`

Second, do you have centrifuge installed? A quick way to check is by running:

`dRep bonus test --check_dependencies`

Finally, when you try this again, include the `-d` option when running the program. This will make some extra output that will make it easier to figure out what the problem is if these things don't fix it.

You can can also try this again without re-running the whole program by just using the command:

`dRep bonus /home/output_dir/ --run_tax --cent_index /home/name/scripts/centrifuge_database/abv -d`

That command will just try the bonus step again on the genome provided during your last run.

Best,
-Matt

**Comment by palomo11** [comment]
I have checked the dependencies:

dRep bonus test --check_dependencies
Loading work directory
Checking dependencies
mash.................................... all good        (location = /services/tools/mash/1.1.1/mash)
nucmer.................................. all good        (location = /services/tools/MUMmer/3.23/nucmer)
checkm.................................. !!! ERROR !!!   (location = /services/tools/anaconda3/4.0.0/bin/checkm)
ANIcalculator........................... all good        (location = /services/tools/anicalculator/1/ANIcalculator)
prodigal................................ all good        (location = /services/tools/prodigal/2.6.3/prodigal)
centrifuge.............................. all good        (location = /services/tools/centrifuge/1.0.3-beta/bin/centrifuge)

ANIcalculator was not loaded before when I run dRep dereplicate, but now it is.

I have just run:

dRep bonus /home/output_dir/ --run_tax --cent_index /home/name/scripts/centrifuge_database/abv -d

Same error as before:

Loading work directory
Running tax
Running Centrifuge
Traceback (most recent call last):
File "/services/tools/anaconda3/4.0.0/bin/dRep", line 26, in 
controller.parseArguments(args)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 144, in parseArguments
self.dereplicate_operation(**vars(args))
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 86, in dereplicate_operation
drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_workflows.py", line 52, in dereplicate_wrapper
drep.d_bonus.d_bonus_wrapper(wd, **kwargs)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 26, in d_bonus_wrapper
run_taxonomy(wd,**kwargs)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 45, in run_taxonomy
Tdb, Bdb = parse_taxonomy(Bdb, cent_dir, **kwargs)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 62, in parse_taxonomy
Tdb = parse_centrifuge_percent(Bdb, cent_dir, **kwargs)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 200, in parse_centrifuge_percent
"{0}{1}_report.tsv".format(cent_dir,genome))
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 340, in parse_raw_centrifuge
tax = pd.read_table(report)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 709, in parser_f
return _read(filepath_or_buffer, kwds)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 449, in _read
parser = TextFileReader(filepath_or_buffer, **kwds)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 818, in init
self._make_engine(self.engine)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
self._engine = CParserWrapper(self.f, **self.options)
File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 1695, in init
self._reader = parsers.TextReader(src, **kwds)
File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.cinit
File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/home/output_dir/data/centrifuge/102_Con1500.fasta_report.tsv' does not exist

Also, in the data folder both prodigal and centrifuge folders are empty:

And again:

Warning: Could not open read file "/home/output_dir/data/centrifuge/103_Con1500.fasta.fna" for reading; skipping...
Error: No input read files were valid
(ERR): centrifuge-class exited with value 1

It seems it is not doing the gene prediction for some reason...

**Comment by MrOlm** [comment]
Very strange... could you upload the folder `/home/output_dir/log/`?

Specifically in the folder `/home/output_dir/log/cmd_logs/` should be a list of the prodigal commands that it tried to run, as well as the output that attempting to run those commands gave.

**Comment by palomo11** [comment]
In cmd_logs there are many files. Here I copy one showing the cmd, the stderr and stdout:

914 Jan 12 18:48 2018-01-12_18.48.40.091859.CMD
392 Jan 12 18:48 2018-01-12_18.48.40.091859.STDERR
0 Jan 12 18:48 2018-01-12_18.48.40.091859.STDOUT

And here what is in them:

cat 2018-01-12_18.48.40.091859.CMD 
/services/tools/centrifuge/1.0.3-beta/bin/centrifuge -f -x /home/name/scripts/centrifuge_database/abv /home/output_dir/data/prodigal/161_Con1500.fasta.fna -S /home/output_dir/data/centrifuge/161_Con1500.fasta_hits.tsv -p 1 --report-file /home/output_dir/data/centrifuge/161_Con1500.fasta_report.tsv

cat 2018-01-12_18.48.40.091859.STDERR 
Warning: Could not open read file "/home/output_dir/data/prodigal/161_Con1500.fasta.fna" for reading; skipping...
Error: No input read files were valid
(ERR): centrifuge-class exited with value 1

cat 2018-01-12_18.48.40.091859.STDERR
empty

It is the same patter for all of them as well as for the ones when I run dRep dereplicate.

In all case it seems it starts directly with centrifuge but not prodigal.

I have searched in the logger.log file when is the first time that the word prodigal appears and it is when trying to run centrifuge:

grep "prodigal" logger.log | head

01-12 15:45 DEBUG    /services/tools/centrifuge/1.0.3-beta/bin/centrifuge -f -x /home/name/scripts/centrifuge_database/ /home/output_dir/data/prodigal/102_Con1500.fasta.fna -S /home/output_dir/data/centrifuge/102_Con1500.fasta_hits.tsv -p 1 --report-file /home/output_dir/data/centrifuge/102_Con1500.fasta_report.tsv

Before that this is what appears in the logger log:

01-12 15:43 DEBUG    nucmer --mum -p /home/output_dir/data/ANImf_files/genome_2/genome_2_vs_genome_2 -c 65 -g 90 /home/output_dir/genome_2 /home/output_dir/genome_2; delta-filter -r -q /home/output_dir/data/ANImf_files/genome_2/genome_2_vs_genome_2.delta > /home/output_dir/data/ANImf_files/genome_2/genome_2_vs_genome_2.delta.filtered
.....
01-12 15:43 DEBUG    Clustering ANIn database
01-12 15:43 DEBUG    making dictionary for average_ani
01-12 15:43 DEBUG    list comprehension for average_ani
01-12 15:43 DEBUG    averageing done
......
01-12 15:43 DEBUG    Saving secondary_linkage pickle /home/output_dir/data/Clustering_files/ to secondary_linkage_cluster_1.pickle
.....
01-12 15:43 INFO     Step 4. Return output
01-12 15:43 DEBUG    Main program run complete- saving output to /home/output_dir/data/
01-12 15:43 INFO     ***************************************************
01-12 15:43 INFO     Loading work directory
01-12 15:43 DEBUG    Located: /home/output_dir
01-12 15:43 DEBUG    Loading provided genome quality information

I hope this can help to solve the problem.

Thank you very much in advance.

**Comment by MrOlm** [comment]
Thank you!

I see the problem now, and just released a new version of dRep (`2.0.5`) with the fix.

You can upgrade with the command `pip install drep --upgrade`, and to make sure you have the right version, you should see the following:

```
$ dRep -h

                ...::: dRep v2.0.5 :::...
```

Thank you for being patient and for helping me catch this bug!

-Matt

**Comment by palomo11** [comment]
Hi Matt,

I have updated the dRep version

dRep -h

                ...::: dRep v2.0.5 :::...

I have try again dRep bonus, but it gives me the same error.

I have tried to run again dRep dereplicate from scratch but I got same error:

> 

Loading work directory
***************************************************
    ..:: dRep dereplicate Step 4. Bonus ::..
***************************************************
    
Loading work directory
Running tax
Running Centrifuge
Traceback (most recent call last):
  File "/services/tools/anaconda3/4.0.0/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_workflows.py", line 52, in dereplicate_wrapper
    drep.d_bonus.d_bonus_wrapper(wd, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 26, in d_bonus_wrapper
    run_taxonomy(wd,**kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 45, in run_taxonomy
    Tdb, Bdb = parse_taxonomy(Bdb, cent_dir, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 62, in parse_taxonomy
    Tdb = parse_centrifuge_percent(Bdb, cent_dir, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 200, in parse_centrifuge_percent
    "{0}{1}_report.tsv".format(cent_dir,genome))
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 340, in parse_raw_centrifuge
    tax = pd.read_table(report)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/home/projects/env_10000/people/alpal/WaterWorks/F17FTSEUET0039_BACggoR/Clean/Alex_1/IDBA_all_TM_meta/all_merged_TM_paired_IDBA_OK/dRep/dRepallRef_allDAS_Con1500_MTB20_MB_metaWRAP/dRepallRef_allDAS_Con1500_MTB20_MB_metaWRAP/data/centrifuge/10_Con1500.fasta_report.tsv' does not 

> exist

It does not seem that prodigal is run...

**Comment by palomo11** [comment]
Hi Matt,

I have an update on the issue.

After running it again now there are outputs both in the prodigal and centrifuge folder.

In the prodigal there are the .fna and the .faa files for all the genomes (around 130) and they look fine, so prodigal seems to run fine.

In the centrifuge folder, there are the report.tsv and hits.tsv files for most of the genomes but the hits.tsv file is empty for 26 of the genomes, and therefore the report.tsv file are absent for those 26 genomes.

The whole bonus process crashed with the same error as reported above, because of course the program could not find some of the report.tsv files and then stopped.

With this info do you know what is going now and how the problem could be solved?

Thanks in advance.

**Comment by MrOlm** [comment]
Hello,

Thank you for the update! I was working on making a different version of the program (with lots of logging information) to try and figure out why prodigal was not able to run, but this now seems like a different issue.

Did you use the `-d` option when running? If so, one of those files in the `log/cmd_logs/` directory should have the reason why centrifuge failed.
 
On a different note, could you let me know if the prodigal output for those 26 genomes is empty?

Thank you,
-Matt

**Comment by palomo11** [comment]
The prodigal output for those 26 genomes is NOT empty, it is fine, similar to the rest of the genomes.

Yes, I run using -d option.

I have checked the STDERR files:


For 7 of them it says:
```
Out of memory allocating the ebwt[] array for the Bowtie index.  Please try
again on a computer with more memory.
Error: Encountered internal Centrifuge exception (#1)
Command: /services/tools/centrifuge/1.0.3-beta/bin/centrifuge-class --wrapper basic-0 -f -x /home/name/centrifuge_database/abv -S /home/name/data/prodigal/bin2_hits.tsv -p 1 --report-file /home/name/data/prodigal/bin2_report.tsv /home/name/data/prodigal/bin2.fna 
(ERR): centrifuge-class exited with value 1
```

For 19 of the genomes it says:
```
(ERR): centrifuge-class died with signal 9 (KILL) 
```

The rest of them:
```
report file /home/name/data/centrifuge/bin.98.fasta_report.tsv
Number of iterations in EM algorithm: 0
Probability diff. (P - P_prev) in the last iteration: 0
Calculating abundance: 00:00:00
```

Thanks!

**Comment by MrOlm** [comment]
Hello,

Thanks for the info. I'm not sure how much more help I can be with this problem, as it now seems to be a problem with Centrifuge and outside the relm of dRep, but there are some things I can think of.

First, by googling those centrifuge errors I found several other people with the same error, as well as some troubleshooting suggestions.

Second, it could be the case that running the jobs in parallel is splitting up the RAM too much and that's what's causing problems. If this is the case, running it with `-p 1` might help.

Third, for each file that ends in `.STDERR`, there should be another file with the same basename but which ends in `.CMD`. This is the exact command that dRep asked your computer to run. If it is the case that running this command works, but it doesn't work within the dRep program, I can try and change some things with how dRep calls the command to see if that makes it work on your computer.

Fourth, you could try setting up centrifuge in a different way. The way that dRep handles taxonomy is based on the way the anvio does it (see here: http://merenlab.org/2016/06/18/importing-taxonomy/). Anvio also provides detailed instructions on how to get centrifuge set up (see here: http://merenlab.org/2016/06/18/installing-third-party-software/#centrifuge), which could fix the problem.

Finally, it may not be worth it for you to spend the time needed to fix this problem. In my experience the taxonomy estimates that result from centrifuge using this method aren't very good anyways, especially for novel organisms, and you'll end up needing to make a tree to verify taxonomy anyways. It is useful for me as a first pass just to get an idea of what the organism probably is, but really not for much more than that.

Best,
-Matt

**Comment by palomo11** [comment]
Thank you very much for the information.

I will try to run it with lower processors and in a computer with more RAM.

But in any case, it was also to have a first idea about the taxonomy of the bins but I will also try other approaches to verify their taxonomy.

Thanks!
