### ISSUE TITLE
Module Not Found Error_sqlite3

### ISSUE THREAD

**Issue by jojyjohn28** [MrOlm/drep#211]
I am trying to de_replicate MAGS. 
But it is showing a module not found error.

Will filter the genome list
54 genomes were input to dRep
Calculating genome info of genomes
Traceback (most recent call last):
  File "/zfs/gcl/software/gbf/python/3.9.7/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/drep/d_workflows.py", line 29, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/drep/d_filter.py", line 73, in d_filter_wrapper
    Gdb = calc_genome_info(bdb['location'].tolist())
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/drep/d_filter.py", line 285, in calc_genome_info
    table['length'].append(calc_fasta_length(loc))
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/drep/d_filter.py", line 665, in calc_fasta_length
    for seq_record in SeqIO.parse(fasta_loc, "fasta"):
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 591, in parse
    from Bio import AlignIO
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/Bio/AlignIO/__init__.py", line 147, in <module>
    from . import MafIO
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/Bio/AlignIO/MafIO.py", line 38, in <module>
    from sqlite3 import dbapi2
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/zfs/gcl/software/gbf/python/3.9.7/lib/python3.9/site-packages/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

I then checked with loaded modules, sqlite/3.38.5-gcc/9.5.0 is already there in the list. Python version is 3.11
(py311) [jojyj@nodelm04 metawrap_70_5_bins]$ module list

Currently Loaded Modules:
  1) mash/2.3                  5) qt/5.15.4-gcc/9.5.0        9) libpng/1.6.37-gcc/9.5.0  13) anicalculator/v1  17) jellyfish/2.3.0          21) ncbi-blast+/2.12.0+  25) drep/3.4.2
  2) mpfr/3.1.6-gcc/8.5.0      6) openssl/1.1.1o-gcc/9.5.0  10) libgd/2.2.4-gcc/9.5.0    14) prodigal/2.6.3    18) gnuplot/5.4.3-gcc/9.5.0  22) gcc/9.3.0            26) anaconda3/2021.11
  3) gmp/6.2.1-gcc/8.5.0       7) mesa/22.0.2-gcc/9.5.0     11) glib/2.72.1-gcc/9.5.0    15) fastANI/1.32      19) mummer/4.0.0rc1          23) python/3.9.7
  **4) sqlite/3.38.5-gcc/9.5.0**   8) libxml2/2.9.13-gcc/9.5.0  12) cairo/1.16.0-gcc/9.5.0   16) swig/4.0.1        20) perl/5.30.1              24) centrifuge/1.0.4

(py311) [jojyj@nodelm04 metawrap_70_5_bins]$ dRep check_dependencies
mash.................................... all good        (location = /zfs/gcl/software/gbf/Mash/2.3/mash)
nucmer.................................. all good        (location = /zfs/gcl/software/gbf/mummer/4.0.0rc1/bin/nucmer)
checkm.................................. all good        (location = /zfs/gcl/software/gbf/python/3.9.7/bin/checkm)
ANIcalculator........................... all good        (location = /zfs/gcl/software/gbf/ANIcalculator/v1/ANIcalculator)
prodigal................................ all good        (location = /zfs/gcl/software/gbf/prodigal/2.6.3/prodigal)
centrifuge.............................. all good        (location = /zfs/gcl/software/gbf/centrifuge/1.0.4/bin/centrifuge)
nsimscan................................ all good        (location = /zfs/gcl/software/gbf/ANIcalculator/v1/nsimscan)
fastANI................................. all good        (location = /zfs/gcl/software/gbf/FastANI/1.32/fastANI)

**Comment by MrOlm** [comment]
Hi @jojyjohn28 - sorry you're encountering this. This is a seems to be a problem with `Biopython`. I'd recommend making a new environment and doing a fresh install of `Biopython`; hopefully that solves it.

Best,
Matt

**Comment by jojyjohn28** [comment]
Hi Matt,
Thank you so much for the quick reply.
I am working on HPC cluster and I do not have any sudo permissions.
However, the hint Biopython from your answer helped me to resolve the issue. I just updated the Biopython as follows 
_pip install Biopython --upgrade_ 
Thanks again.

**Comment by MrOlm** [comment]
Great! Glad I could help.

Best,
Matt
