### ISSUE TITLE
Empty distance matrix error

### ISSUE THREAD

**Issue by MundaneAD** [MrOlm/drep#212]
Hi,
I am trying to run dRep compare on about 2500 genomes. Here is the error file:
```
***************************************************
    ..:: dRep compare Step 1. Cluster ::..
***************************************************

Running primary clustering
Running pair-wise MASH clustering
Traceback (most recent call last):
  File "/home/belger/miniconda3/envs/foo/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/drep/controller.py", line 102, in parseArguments
    self.compare_operation(**vars(args))
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/drep/controller.py", line 53, in compare_operation
    drep.d_workflows.compare_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/drep/d_workflows.py", line 97, in compare_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/drep/d_cluster/controller.py", line 184, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/drep/d_cluster/compare_utils.py", line 115, in all_vs_all_MASH
    Cdb, cluster_ret = cluster_mash_database(Mdb, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/drep/d_cluster/compare_utils.py", line 280, in cluster_mash_database
    Cdb, linkage = drep.d_cluster.cluster_utils.cluster_hierarchical(linkage_db, linkage_method= P_Lmethod, \
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/drep/d_cluster/cluster_utils.py", line 114, in cluster_hierarchical
    linkage = scipy.cluster.hierarchy.linkage(arr, method= linkage_method)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/scipy/cluster/hierarchy.py", line 1067, in linkage
    n = int(distance.num_obs_y(y))
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/belger/miniconda3/envs/foo/lib/python3.11/site-packages/scipy/spatial/distance.py", line 2630, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
```
Here is my sbatch script
```
#!/bin/bash
#SBATCH --time=30:00           # this is in minutes
#SBATCH --cpus-per-task=16      # number of cores
#SBATCH --mem=128G             # memory allocation
#SBATCH --output=/spaces/belger/lion_output/leo_out/DRep/DRep_compare_output/output_file.log
#SBATCH --error=/spaces/belger/lion_output/leo_out/DRep/DRep_compare_output/error_file.log

conda run -n foo dRep compare /spaces/belger/lion_output/leo_out/DRep/DRep_compare_output -g /spaces/belger/ftp.tue.mpg.de/ebio/projects/animal_gut_metagenome_assembly/MAGs/fasta/*
```
Here is my dRep check_dependencies
```
dRep check_dependencies
mash.................................... all good        (location = /home/belger/miniconda3/envs/foo/bin/mash)
nucmer.................................. all good        (location = /home/belger/miniconda3/envs/foo/bin/nucmer)
checkm.................................. !!! ERROR !!!   (location = None)
ANIcalculator........................... !!! ERROR !!!   (location = None)
prodigal................................ all good        (location = /home/belger/miniconda3/envs/foo/bin/prodigal)
centrifuge.............................. !!! ERROR !!!   (location = None)
nsimscan................................ !!! ERROR !!!   (location = None)
fastANI................................. all good        (location = /home/belger/miniconda3/envs/foo/bin/fastANI)
```
Can anyone tell what might be going wrong?

**Comment by MrOlm** [comment]
Hi @MundaneAD - bizare. It seems like your `mash` command is failing, even though dRep thinks it's installed properly. I would recommend running again with the `-d` option. This will create a bunch of files in the `log` folder that will let you know what errors mash is encountering.

Best,
Matt

**Comment by MundaneAD** [comment]
Hi @MrOlm This is what is in the log file when I try to run on my ~2500 genomes
```
    ..:: dRep compare Step 1. Cluster ::..
***************************************************

11-16 11:24 INFO     Running primary clustering
11-16 11:24 INFO     Running pair-wise MASH clustering
11-16 11:25 DEBUG    Clustering MASH database
11-16 11:37 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
11-16 11:37 DEBUG    ***Logger started up at /spaces/belger/lion_output/leo_out/DRep/DRep_compare_output/log/logger.log***
11-16 11:37 DEBUG    Command to run dRep was: /home/belger/miniconda3/envs/foo/bin/dRep compare /spaces/belger/lion_output/leo_out/DRep/DRep_compare_output -g /spaces/belger/ftp.tue.mpg.de/ebio/projects/animal_gut_metagenome_assembly/MA$
11-16 11:37 DEBUG    dRep version 3.4.5 was run

11-16 11:37 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

11-16 11:37 DEBUG    Namespace(operation='compare', work_directory='/spaces/belger/lion_output/leo_out/DRep/DRep_compare_output', processors=6, debug=False, genomes=['/spaces/belger/ftp.tue.mpg.de/ebio/projects/animal_gut_metagenome_ass$11-16 11:37 DEBUG    Starting the compare operation
11-16 11:37 INFO     ***************************************************
```
This is in the log file when I try run it on a subset of 17 genomes
```

    ..:: dRep compare Step 1. Cluster ::..
***************************************************

11-15 11:22 INFO     Running primary clustering
11-15 11:22 INFO     Running pair-wise MASH clustering
11-15 11:22 DEBUG    Clustering MASH database
11-15 11:22 DEBUG    Saving primary_linkage pickle to /spaces/belger/lion_output/leo_out/DRep/DRep_compare_output/data/Clustering_files/
11-15 11:22 INFO     17 primary clusters made
11-15 11:22 INFO     Running secondary clustering
11-15 11:22 INFO     Running 17 fastANI comparisons- should take ~ 1.6 min
11-15 11:22 DEBUG    running cluster 3
11-15 12:20 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
11-15 12:20 DEBUG    ***Logger started up at /spaces/belger/lion_output/leo_out/DRep/DRep_compare_output/log/logger.log***
11-15 12:20 DEBUG    Command to run dRep was: /home/belger/miniconda3/envs/foo/bin/dRep compare /spaces/belger/lion_output/leo_out/DRep/DRep_compare_output -g /spaces/belger/ftp.tue.mpg.de/ebio/projects/animal_gut_metagenome_assembly/MA$
11-15 12:20 DEBUG    dRep version 3.4.5 was run

11-15 12:20 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

11-15 12:20 DEBUG    Namespace(operation='compare', work_directory='/spaces/belger/lion_output/leo_out/DRep/DRep_compare_output', processors=16, debug=False, genomes=['/spaces/belger/ftp.tue.mpg.de/ebio/projects/animal_gut_metagenome_as$11-15 12:20 DEBUG    Starting the compare operation
11-15 12:20 INFO     ***************************************************
```

**Comment by MrOlm** [comment]
It fails in both cases, yes? If you ran with -d there should also be a folder called cmd_logs with logs of files in it. Those are what we’re after

**Comment by MundaneAD** [comment]
I managed to run it by logging into a node using `srun` instead of using `sbtach`.
Thanks for the help Matt and sorry to bother!
