### ISSUE TITLE
Issue with ANImf: 0% ANI despite similar nucleotide sequences

### ISSUE THREAD

**Issue by vsanchez0** [MrOlm/drep#223]
I am currently trying to run dereplication on a number of genomes. I am comparing the performance of the secondary clustering algorithm fastANI to ANImf. When I run the tool with ANImf, I am told that all my genomes have a 0% ANI, even those previously classified by fastANI as having a nearly identical nucleotide sequence. Any insights as to why this is?

Here's the full output message.

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************

Will filter the genome list
1,091 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************

Running primary clustering
Running pair-wise MASH clustering
542 primary clusters made
Running secondary clustering
Running 4369 ANImf comparisons- should take ~ 68.3 min
Step 4. Return output
***************************************************
    ..:: dRep dereplicate Step 3. Choose ::..
***************************************************

Loading work directory
***************************************************
    ..:: dRep dereplicate Step 4. Evaluate ::..
***************************************************

will produce Widb (winner information db)
Winner database saved to /dRep_ANImfdata_tables/Widb.csv
***************************************************
    ..:: dRep dereplicate Step 5. Analyze ::..
***************************************************

making plots 1, 2, 3, 4, 5, 6
Plotting primary dendrogram
Plotting secondary dendrograms
Plotting MDS plot
Plotting scatterplots
Plotting bin scorring plot
Failed to make plot #5: list index out of range
Traceback (most recent call last):
  File "/anaconda3/envs/drep/lib/python3.9/site-packages/drep/d_analyze.py", line 108, in d_ana
lyze_wrapper
    plot_binscoring_from_wd(wd, plot_dir, **kwargs)
  File "/anaconda3/envs/drep/lib/python3.9/site-packages/drep/d_analyze.py", line 369, in plot_
binscoring_from_wd
    plot_winner_scoring_complex(Wdb, Sdb, Cdb, Gdb, plot_dir = plot_dir, **kwargs)
  File "/anaconda3/envs/drep/lib/python3.9/site-packages/drep/d_analyze.py", line 734, in plot_
winner_scoring_complex
    g.annotate("{0:.1f}".format(vals[i]), (p.get_width(), p.get_y()+(p.get_height()/1.1) ), fontsize=8)
IndexError: list index out of range
Plotting winning genomes plot...
Failed to make plot #6: list index out of range
Traceback (most recent call last):
  File "/anaconda3/envs/drep/lib/python3.9/site-packages/drep/d_analyze.py", line 117, in d_ana
lyze_wrapper
    plot_winners_from_wd(wd, plot_dir, **kwargs)
  File "/anaconda3/envs/drep/lib/python3.9/site-packages/drep/d_analyze.py", line 403, in plot_
winners_from_wd
    plot_winners(Wdb, Gdb, Wndb, Wmdb, Widb, plot_dir = plot_dir, **kwargs)
  File "/anaconda3/envs/drep/lib/python3.9/site-packages/drep/d_analyze.py", line 840, in plot_
winners
    _make_scoring_plot(d,bars,**kwargs)
  File "/anaconda3/envs/drep/lib/python3.9/site-packages/drep/d_analyze.py", line 1384, in _mak
e_scoring_plot
    g.annotate("{0:.1f}".format(vals[i]), (p.get_width(), p.get_y()+(p.get_height()/1.1) ), fontsize=8)
IndexError: list index out of range

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

    ..:: dRep dereplicate finished ::..

Dereplicated genomes................. /dRep_ANImf/dereplicated_genomes/
Dereplicated genomes information..... /dRep_ANImf/data_tables/Widb.csv
Figures.............................. /dRep_ANImf/figures/
Warnings............................. /dRep_ANImf/log/warnings.txt

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
```

**Comment by MrOlm** [comment]
Hi @vsanchez0 - could it be the genomes being compared are below the alignment coverage threshold? How are you comparing the values- with the plots or the `Ndb.csv` file?

Best,
Matt

**Comment by vsanchez0** [comment]
I am using the default alignment coverage threshold. This wasn't an issue with fastANI.
I am comparing the values with the `Ndb.csv` file

**Comment by MrOlm** [comment]
OK- this definitely sounds like an issue with ANImf. Please run again with the `-d` flag, which will create a folder of command log files in the `log` folder. We can check those out to see what errors it's throwing. Feel free to run on a subset of genomes, since it's likely the same issue for all genomes

-Matt

**Comment by vsanchez0** [comment]
I originally ran with that flag!
Here is part of the Step 2 report. I'm not familiar with what it is supposed to look like, let me know if you'd like to look at other parts or if it'd be easier to send the whole report to you.

```
01-09 13:29 INFO     ***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
01-09 13:29 INFO     Running primary clustering
01-09 13:29 INFO     Running pair-wise MASH clustering
01-09 13:29 DEBUG    Clustering MASH database
01-09 13:29 DEBUG    Debug mode on - saving Mdb ASAP
01-09 13:29 DEBUG    Debug mode on - saving CdbF ASAP
01-09 13:29 DEBUG    Saving primary_linkage pickle to dRep_ANImf/data/Clustering_files/
01-09 13:29 INFO     542 primary clusters made
01-09 13:29 INFO     Running secondary clustering
01-09 13:29 INFO     Running 4369 ANImf comparisons- should take ~ 68.3 min
01-09 13:29 DEBUG    running cluster 387
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR385984.contigs.fasta/DRR385984.contigs.fasta_vs_DRR385984.contigs.fasta -c 65 -g 90 DRR385984.contigs.fasta DRR385984.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR385984.contigs.fasta/DRR385984.contigs.fasta_vs_DRR385984.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/DRR385984.contigs.fasta/DRR385984.contigs.fasta_vs_DRR385984.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR385984.contigs.fasta/DRR385984.contigs.fasta_vs_DRR386005.contigs.fasta -c 65 -g 90 DRR385984.contigs.fasta DRR386005.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR385984.contigs.fasta/DRR385984.contigs.fasta_vs_DRR386005.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/DRR385984.contigs.fasta/DRR385984.contigs.fasta_vs_DRR386005.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386005.contigs.fasta/DRR386005.contigs.fasta_vs_DRR385984.contigs.fasta -c 65 -g 90 DRR386005.contigs.fasta DRR385984.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386005.contigs.fasta/DRR386005.contigs.fasta_vs_DRR385984.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386005.contigs.fasta/DRR386005.contigs.fasta_vs_DRR385984.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386005.contigs.fasta/DRR386005.contigs.fasta_vs_DRR386005.contigs.fasta -c 65 -g 90 DRR386005.contigs.fasta DRR386005.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386005.contigs.fasta/DRR386005.contigs.fasta_vs_DRR386005.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386005.contigs.fasta/DRR386005.contigs.fasta_vs_DRR386005.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    running cluster 395
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_DRR386058.contigs.fasta -c 65 -g 90 DRR386058.contigs.fasta DRR386058.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_DRR386058.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_DRR386058.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_DRR386547.contigs.fasta -c 65 -g 90 DRR386058.contigs.fasta DRR386547.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_DRR386547.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_DRR386547.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_GCA_018420215.1.fasta -c 65 -g 90 DRR386058.contigs.fasta GCA_018420215.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_GCA_018420215.1.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_GCA_018420215.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_GCA_023337115.1.fasta -c 65 -g 90 DRR386058.contigs.fasta GCA_023337115.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_GCA_023337115.1.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_GCA_023337115.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_GCA_900509245.1.fasta -c 65 -g 90 DRR386058.contigs.fasta GCA_900509245.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_GCA_900509245.1.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386058.contigs.fasta/DRR386058.contigs.fasta_vs_GCA_900509245.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_DRR386058.contigs.fasta -c 65 -g 90 DRR386547.contigs.fasta DRR386058.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_DRR386058.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_DRR386058.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_DRR386547.contigs.fasta -c 65 -g 90 DRR386547.contigs.fasta DRR386547.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_DRR386547.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_DRR386547.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_GCA_018420215.1.fasta -c 65 -g 90 DRR386547.contigs.fasta GCA_018420215.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_GCA_018420215.1.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_GCA_018420215.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_GCA_023337115.1.fasta -c 65 -g 90 DRR386547.contigs.fasta GCA_023337115.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_GCA_023337115.1.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_GCA_023337115.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_GCA_900509245.1.fasta -c 65 -g 90 DRR386547.contigs.fasta GCA_900509245.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_GCA_900509245.1.fasta.delta > dRep_ANImf/data/ANImf_files/DRR386547.contigs.fasta/DRR386547.contigs.fasta_vs_GCA_900509245.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_DRR386058.contigs.fasta -c 65 -g 90 GCA_018420215.1.fasta DRR386058.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_DRR386058.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_DRR386058.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_DRR386547.contigs.fasta -c 65 -g 90 GCA_018420215.1.fasta DRR386547.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_DRR386547.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_DRR386547.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_GCA_018420215.1.fasta -c 65 -g 90 GCA_018420215.1.fasta GCA_018420215.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_GCA_018420215.1.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_GCA_018420215.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_GCA_023337115.1.fasta -c 65 -g 90 GCA_018420215.1.fasta GCA_023337115.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_GCA_023337115.1.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_GCA_023337115.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_GCA_900509245.1.fasta -c 65 -g 90 GCA_018420215.1.fasta GCA_900509245.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_GCA_900509245.1.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_018420215.1.fasta/GCA_018420215.1.fasta_vs_GCA_900509245.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_DRR386058.contigs.fasta -c 65 -g 90 GCA_023337115.1.fasta DRR386058.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_DRR386058.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_DRR386058.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_DRR386547.contigs.fasta -c 65 -g 90 GCA_023337115.1.fasta DRR386547.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_DRR386547.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_DRR386547.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_GCA_018420215.1.fasta -c 65 -g 90 GCA_023337115.1.fasta GCA_018420215.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_GCA_018420215.1.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_GCA_018420215.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_GCA_023337115.1.fasta -c 65 -g 90 GCA_023337115.1.fasta GCA_023337115.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_GCA_023337115.1.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_GCA_023337115.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_GCA_900509245.1.fasta -c 65 -g 90 GCA_023337115.1.fasta GCA_900509245.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_GCA_900509245.1.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_023337115.1.fasta/GCA_023337115.1.fasta_vs_GCA_900509245.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_DRR386058.contigs.fasta -c 65 -g 90 GCA_900509245.1.fasta DRR386058.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_DRR386058.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_DRR386058.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_DRR386547.contigs.fasta -c 65 -g 90 GCA_900509245.1.fasta DRR386547.contigs.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_DRR386547.contigs.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_DRR386547.contigs.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_GCA_018420215.1.fasta -c 65 -g 90 GCA_900509245.1.fasta GCA_018420215.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_GCA_018420215.1.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_GCA_018420215.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_GCA_023337115.1.fasta -c 65 -g 90 GCA_900509245.1.fasta GCA_023337115.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_GCA_023337115.1.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_GCA_023337115.1.fasta.delta.filtered
01-09 13:29 DEBUG    nucmer --mum -p dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_GCA_900509245.1.fasta -c 65 -g 90 GCA_900509245.1.fasta GCA_900509245.1.fasta; delta-filter -r -q dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_GCA_900509245.1.fasta.delta > dRep_ANImf/data/ANImf_files/GCA_900509245.1.fasta/GCA_900509245.1.fasta_vs_GCA_900509245.1.fasta.delta.filtered

```

**Comment by MrOlm** [comment]
OK great! In the log folder there should a folder named something like `cmd_logs` with a bunch of files in it. These files contain the STDOUT and STDERR of each nucmer command (and all other commands). Please either upload the folder here, or paste in the contents of some of the files.

Best,
Matt

**Comment by vsanchez0** [comment]
[logger_ANImf.log](https://github.com/MrOlm/drep/files/13891099/logger_ANImf.log)

**Comment by vsanchez0** [comment]
Is this what you're looking for?
[logger_ANImf.log](https://github.com/MrOlm/drep/files/13891136/logger_ANImf.log)

**Comment by MrOlm** [comment]
Nope- it's a folder called `cmd_logs`. See below. If it's not there, could you let me know what dRep version you're running? If it's not the latest, try running with `-d` again in a new work_directory.

```
$ ls
data  data_tables  dereplicated_genomes  figures  log

$ ls log/
cluster_arguments.json  cmd_logs  logger.log  warnings.txt

$ ls log/cmd_logs/
2024-01-10_09.49.47.964414.CMD     2024-01-10_09.49.47.964414.STDOUT  2024-01-10_09.49.53.010763.STDERR
2024-01-10_09.49.47.964414.STDERR  2024-01-10_09.49.53.010763.CMD     2024-01-10_09.49.53.010763.STDOUT
```

**Comment by vsanchez0** [comment]
[2024-01-09_13.30.28.627697.STDOUT.txt](https://github.com/MrOlm/drep/files/13891213/2024-01-09_13.30.28.627697.STDOUT.txt)
[2024-01-09_13.30.28.627697.STDERR.txt](https://github.com/MrOlm/drep/files/13891214/2024-01-09_13.30.28.627697.STDERR.txt)

**Comment by MrOlm** [comment]
Ah- from the STDERR it seems like your don't have `nucmer` or `delta-filter` installed. Theses are part of the `mummer` suite of tools and are needed for ANImf to work.

Best,
Matt

**Comment by vsanchez0** [comment]
This solved it! Thank you so much

**Comment by MrOlm** [comment]
Great, glad it's working!
