### ISSUE TITLE
ValueError: mash isn't working- make sure its installed

### ISSUE THREAD

**Issue by soojunglee98** [MrOlm/drep#232]
I am running deep but I got this error message 
ValueError: mash isn't working- make sure its installed

**This is the log file of the job and in my checkM Conda environment, I do have MASH installed.. This is my program list in checkM Conda environment. I tried to reinstall MASH in this environment and re-run the code, but it got the same error. What would be the next step?**

```
[2024-06-08 19:50:45] INFO: CheckM v1.2.1
[2024-06-08 19:50:45] INFO: checkm data setRoot
[2024-06-08 19:50:45] INFO: CheckM data: /home/lsoojung/miniconda3/envs/checkm/checkm_data
[2024-06-08 19:50:45] INFO: [CheckM - data] Check for database updates. [setRoot]
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
1,015 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Running checkM
51.43% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
Traceback (most recent call last):
  File "/home/lsoojung/miniconda3/envs/checkm/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/home/lsoojung/miniconda3/envs/checkm/lib/python3.10/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/lsoojung/miniconda3/envs/checkm/lib/python3.10/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/lsoojung/miniconda3/envs/checkm/lib/python3.10/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/home/lsoojung/miniconda3/envs/checkm/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 184, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/home/lsoojung/miniconda3/envs/checkm/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/home/lsoojung/miniconda3/envs/checkm/lib/python3.10/site-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
  File "/home/lsoojung/miniconda3/envs/checkm/lib/python3.10/site-packages/drep/d_cluster/compare_utils.py", line 102, in all_vs_all_MASH
    logdir, MASH_folder, sketch_folder, mash_exe = prepare_mash(data_folder, **kwargs)
  File "/home/lsoojung/miniconda3/envs/checkm/lib/python3.10/site-packages/drep/d_cluster/compare_utils.py", line 137, in prepare_mash
    mash_exe = drep.get_exe('mash')
  File "/home/lsoojung/miniconda3/envs/checkm/lib/python3.10/site-packages/drep/__init__.py", line 100, in get_exe
    raise ValueError("{0} isn't working- make sure its installed".format(name))
ValueError: mash isn't working- make sure its installed`
```

```

# packages in environment at /home/lsoojung/miniconda3/envs/checkm:

 #Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
blas                      1.0                    openblas  
bottleneck                1.3.7           py310ha9d4c09_0  
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.6.2             hbcca054_0    conda-forge
capnproto                 1.0.2                h2b92303_1    conda-forge
certifi                   2024.6.2        py310h06a4308_0  
checkm-genome             1.2.1              pyhdfd78af_0    bioconda
contourpy                 1.2.1           py310hd41b1e2_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dendropy                  5.0.1              pyhdfd78af_0    bioconda
drep                      3.5.0              pyhdfd78af_0    bioconda
fastani                   1.34                 h4dfc31f_2    bioconda
fonttools                 4.53.0          py310hc51659f_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gettext                   0.22.5               h59595ed_2    conda-forge
gettext-tools             0.22.5               h59595ed_2    conda-forge
gsl                       2.7.1                h6e86dc7_1  
hmmer                     3.4                  hdbdd923_1    bioconda
joblib                    1.4.0           py310h06a4308_0  
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py310hd41b1e2_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libasprintf               0.22.5               h661eb56_2    conda-forge
libasprintf-devel         0.22.5               h661eb56_2    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libcurl                   8.8.0                hca28451_0    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h77fa898_7    conda-forge
libgettextpo              0.22.5               h59595ed_2    conda-forge
libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
libgfortran-ng            13.2.0               h69a702a_7    conda-forge
libgfortran5              13.2.0               hca663fb_7    conda-forge
libgomp                   13.2.0               h77fa898_7    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.45.3               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
mash                      2.3                  hc74b729_7    bioconda
matplotlib-base           3.8.4           py310hef631a5_2    conda-forge
mummer4                   4.0.0rc1        pl5321hdbdd923_6    bioconda
munkres                   1.0.7                      py_1    bioconda
ncurses                   6.5                  h59595ed_0    conda-forge
numexpr                   2.8.7           py310h286c3b5_0  
numpy                     1.26.4          py310hb13e2d6_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.1                h4ab18f5_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.1           py310h6a678d5_0  
perl                      5.32.1          0_h5eee18b_perl5  
pillow                    10.3.0          py310hf73ecf8_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pplacer                   1.1.alpha19          h9ee0642_2    bioconda
prodigal                  2.6.3                h031d066_9    bioconda
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysam                     0.22.1          py310h41dec4a_0    bioconda
python                    3.10.14         hd12c33a_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.10                    4_cp310    conda-forge
pytz                      2024.1          py310h06a4308_0  
readline                  8.2                  h8228510_1    conda-forge
scikit-learn              1.4.2           py310h1128e8f_1  
scipy                     1.13.1          py310h93e2701_0    conda-forge
seaborn                   0.12.2          py310h06a4308_0  
setuptools                70.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
skani                     0.2.1                h4ac6f70_0    bioconda
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.66.4          py310h2f386ee_0  
tzdata                    2024a                h0c530f3_0    conda-forge
unicodedata2              15.1.0          py310h2372a71_0    conda-forge
wget                      1.21.4               hda4d442_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

`
```

**Comment by MrOlm** [comment]
Hi @soojunglee98 - two things. 1) if you run dRep --check_dependencies, it will tell you if it has proper access to mash or not. that way you can know if the run is going to fail or not without waiting. 2) try running `mash -h`; my guess is that it needs more dependencies that you don't have.

Best,
Matt

**Comment by soojunglee98** [comment]
it did work! I did `mash -h` and found what is missing. Thank you so much
