### ISSUE TITLE
assert os.path.isfile(genome), "{0} is not a file".format(genome) AssertionError: ......./b1.fasta is not a file

### ISSUE THREAD

**Issue by Joedhy** [MrOlm/drep#236]
hello, I've met a same error similar to #50 ,however ,I checked my file path, and file content,which is a real .fasta file. I don't know how to fix it. 
this is the error 
```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************

Will filter the genome list
Traceback (most recent call last):
  File "/public/home/fudan_bio/dinghy/miniconda3/envs/drep/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/public/home/fudan_bio/dinghy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/public/home/fudan_bio/dinghy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/public/home/fudan_bio/dinghy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_workflows.py", line 29, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/public/home/fudan_bio/dinghy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_filter.py", line 63, in d_filter_wrapper
    bdb = drep.d_cluster.utils.load_genomes(kwargs['genomes'])
  File "/public/home/fudan_bio/dinghy/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_cluster/utils.py", line 605, in load_genomes
    assert os.path.isfile(genome), "{0} is not a file".format(genome)
AssertionError: ./BIN_REFINEMENT/SRR1761666/metawrap_70_5_bins/b1.fasta is not a file
```

this is my command
```
source activate drep
dRep dereplicate ./DREP -p 6 -con 5 -comp 70 -sa 0.95 -g ./BIN_REFINEMENT/SRR1761666/metawrap_70_5_bins/b1.fasta ./BIN_REFINEMENT/SRR1761666/metawrap_70_5_bins/b2.fasta
```

I have also checked the path
```
head ./BIN_REFINEMENT/SRR1761666/metawrap_70_5_bins/b1.fasta
>k141_29163_length_15012_cov_6.4179
AGCCATACGCTTCCATGACAGTTATGTACTTCGCTATGTTTAGTACATTTATGTATTACACATTGAATATTCTCACTCCTCTATCTCAATCCCCATGATA
GGTTCCCAATCAGCCAAAGTTCTTTCAGACGTTGGACTTTTAATATATACATGTAACTTATCAATATCAAATTCTAATCCTCTTGCACCACTCATTCCAG
```
I also used Regular expression like *.fasta or *.fa ,but got the same error

**Comment by Joedhy** [comment]
solution:
use Absolute path !

**Comment by MrOlm** [comment]
Hi @Joedhy - weird that python is not able to interpret relative paths in this way. Thank you for posting the solution, as well!

Best,
Matt
