### ISSUE TITLE
dRep failes when no genome passes the filtering step

### ISSUE THREAD

**Issue by fungs** [MrOlm/drep#26]
Hi, as recommended in #25 I ran dRep with this option but it seems this is not implemented correctly in the current version:

```
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Clustering Step 1. Parse Arguments
Clustering Step 2. Perform MASH (primary) clustering
2. Nevermind! Skipping Mash
0 primary clusters made
Step 3. Perform secondary clustering
Running 0 ANImf comparisons- should take ~ 0.0 min
Traceback (most recent call last):
  File "/home/johdro/.conda/envs/drep/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/drep/d_workflows.py", line 36, in dereplicate_wrapper
    drep.d_cluster.d_cluster_wrapper(wd, **kwargs)
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/drep/d_cluster.py", line 75, in d_cluster_wrapper
    data_folder, wd=workDirectory, **kwargs)
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/drep/d_cluster.py", line 175, in cluster_genomes
    Cdb, c2ret = _cluster_Ndb(Ndb, comp_method=algorithm, **kwargs)
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/drep/d_cluster.py", line 207, in _cluster_Ndb
    for name, ndb in Ndb.groupby(id):
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/pandas/core/generic.py", line 5162, in groupby
    **kwargs)
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/pandas/core/groupby.py", line 1848, in groupby
    return klass(obj, by, **kwds)
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/pandas/core/groupby.py", line 516, in __init__
    mutated=self.mutated)
  File "/home/johdro/.conda/envs/drep/lib/python3.6/site-packages/pandas/core/groupby.py", line 2934, in _get_grouper
    raise KeyError(gpr)
KeyError: 'primary_cluster'
```

Apparently, skipping MASH produces zero primary clusters and this leads to errors.

Command line used was

    dRep dereplicate -pa 0.8 -sa 0.98 -comp 25 -con 25 -l 20000 -p 1 --SkipMash drep_out -g *.fna

Best,
Johannes

**Comment by MrOlm** [comment]
Hi Johannes,

That's really weird...

It seems like this would happen if 1) all your genomes got filtered out, or 2) the `*.fna` isn't hitting any genomes.

In the `data_tables/` folder, there should be a file called `Bdb.csv`. Does that have any genomes in it?

Additionally, with the above step (the filtering step), does it say something like `X genomes passed quality filtering`?

-Matt

**Comment by fungs** [comment]
You are right, it seems to be the filtering, though this shouldn't result in an error like this IMO.

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
50.00% of genomes passed length filtering
Running prodigal
Running checkM
0.00% of genomes passed checkM filtering
```

`Bdb.csv' is empty, accordingly. I suppose it's easy to fix and stop after step 1, if now genome passes the filtering. Similarly, I would try to catch an empty list of files in the input to improve the usability.

BTW: What happens, if file names or sequences IDs contain commas, is that escaped in the CSV files? Wouldn't it be better to report using tab-separated TSV files?

Best,
Johannes

**Comment by MrOlm** [comment]
Hi Johannes,

Thanks for the suggestion- will add to my internal to-do list.

As for the commas, they are current not escaped. You are right that maybe I should have done TSV files from the get-go, but as it would be a pain to change now and because commas in filenames are very rare, I will probably not change it unless it becomes a bigger issue.

Best,
-Matt

**Comment by fungs** [comment]
Hi Matt,

what about leaving bug reports open until they have been addressed in a commit?

PS: I do have commas in many files.
