### ISSUE TITLE
Something worng while running evaluate module

### ISSUE THREAD

**Issue by Zhong17** [MrOlm/drep#41]
I run the module respectively， command: dRep evaluate work_dir -e a , and get the error like this:

will compare winners
will provide warnings about clusters
2 warnings generated: saved to /stor9000/apps/users/NWSUAF/2013130172/Jingrx/drep/log/warnings.txt
will produce Widb (winner information db)
Traceback (most recent call last):
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/pandas/core/indexes/bas
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Bin Id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/drep/controller.py", li
    self.evaluate_operation(**vars(args))
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/drep/controller.py", li
    drep.d_evaluate.d_evaluate_wrapper(kwargs['work_directory'],**kwargs)
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/drep/d_evaluate.py", li
    Widb = evaluate_winners(wd, **kwargs)
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/drep/d_evaluate.py", li
    d = Chdb[Chdb['Bin Id'] == row['genome']]
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/pandas/core/frame.py", 
    return self._getitem_column(key)
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/pandas/core/frame.py", 
    return self._get_item_cache(key)
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/pandas/core/generic.py"
    values = self._data.get(item)
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/pandas/core/internals.p
    loc = self.items.get_loc(item)
  File "/stor9000/apps/users/NWSUAF/2013130172/software/miniconda_dRep/lib/python3.6/site-packages/pandas/core/indexes/bas
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Bin Id'
 I wonder what's wrong with the Bin id?

**Comment by Zhong17** [comment]
by the way, the data_table fail to get Widb.csc, but Wmdb.csv and Wndb.csv instead, Is anyone know what's Wmdb file and Wndb.csv file?

**Comment by Zhong17** [comment]
the Chdb.csv were generated from checkM and add in the data_table, after running cluster step, and then run the choose step.

**Comment by MrOlm** [comment]
I see. So this is a slightly complicated situation with dRep. Could you send me the very top of your Chdb.csv file? It would be helpful to know what column names you have.

Best,
-Matt
