### ISSUE TITLE
Breaks if stopped during checkM stage, but restarts if delete checkM dir

### ISSUE THREAD

**Issue by alexdthomas** [MrOlm/drep#43]
Hi Matt, 

Not sure this is an issue, but I'm leaving this here for posterity.  

I've stopped dRep in different stages and restarted it and it usually works better than I would expect.  This seems to be correct given the documentations statement 

> Work Directory
The work directory is where all of the program’s internal workings, log files, cached data, and output is stored. When running dRep modules multiple times on the same dataset, it is essential that you use the same work directory so the program can find the results of previous runs.
https://drep.readthedocs.io/en/latest/module_descriptions.html

However, if dRep is stopped during the checkM stage and restarted, it crashes and reports the same error it does when pyenv is not set to both the python3 version with dRep installed and the python2 version with checkM installed. 

Example
```
pyenv local 3.6.1 miniconda2-latest
dRep dereplicate test_checkM -g tests/genomes/*
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************

Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Running checkM

#control+c to stop dRep
^CTraceback (most recent call last):
  File "/home/talex/.pyenv/versions/3.6.1/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/drep/d_workflows.py", line 28, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/drep/d_filter.py", line 81, in d_filter_wrapper
    Gdb = _get_run_genomeInfo(wd, bdb, **kwargs)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/drep/d_filter.py", line 141, in _get_run_genomeInfo
    Chdb = _run_checkM_wrapper(bdb, workDirectory, **kwargs)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/drep/d_filter.py", line 363, in _run_checkM_wrapper
    Chdb = run_checkM(prod_folder, checkM_outfolder, wd=workDirectory, **kwargs)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/drep/d_filter.py", line 512, in run_checkM
    drep.run_cmd(cmd, shell=False, logdir=logdir)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/drep/__init__.py", line 47, in run_cmd
    call(cmd,stdout=sto, stderr=ste)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 1439, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 1386, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

#restart 
dRep dereplicate test_checkM -g tests/genomes/*
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************

Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Past prodigal runs found- will not re-run
Running checkM
!!! checkM failed !!!
If using pyenv, make sure both python2 and python3 are available (for example: pyenv global 3.5.1 2.7.9)
```

If I delete `test_checkM/data/checkM` though, dRep restarts just fine 

```
rm -r test_checkM/data/checkM/
Rep dereplicate test_checkM -g tests/genomes/*
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************

Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Past prodigal runs found- will not re-run
Running checkM
100.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************

#etc ... ran to completion
```

Like I said, not sure this is really an issue, but it was confusing for me for a bit... 

Cheers, 
Alex

**Comment by MrOlm** [comment]
Thanks for posting this in case others run into the same issue!
