### ISSUE TITLE
os.path.isfile(genome), "{0} is not a file".format(genome)

### ISSUE THREAD

**Issue by MeggyC** [MrOlm/drep#50]
Hey there, 
I am attempting to use viral contigs (from VirSorter) as "genomes", but I get an error 
`Traceback (most recent call last):
  File "/srv/sw/miniconda3/envs/dRep_2.2.4/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/srv/sw/miniconda3/envs/dRep_2.2.4/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/srv/sw/miniconda3/envs/dRep_2.2.4/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/srv/sw/miniconda3/envs/dRep_2.2.4/lib/python3.6/site-packages/drep/d_workflows.py", line 28, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/srv/sw/miniconda3/envs/dRep_2.2.4/lib/python3.6/site-packages/drep/d_filter.py", line 65, in d_filter_wrapper
    bdb = drep.d_cluster.load_genomes(kwargs['genomes'])
  File "/srv/sw/miniconda3/envs/dRep_2.2.4/lib/python3.6/site-packages/drep/d_cluster.py", line 1175, in load_genomes
    assert os.path.isfile(genome), "{0} is not a file".format(genome)
AssertionError: /concatenatedASSVirs/04042019_concatenated_VirSorter_output_for_dRep_cats123/assembly*.fasta is not a file` 

When I attempt to run the following command: 

`$ dRep dereplicate workingdirectory/ -sa 0.97 -l 1000 -g /path/assembly*.fasta`
How can I format my viral contigs so that they can be accepted as genome files? i.e. what are the requirements of a genome file?

**Comment by MrOlm** [comment]
Hello,

Thank you for the detailed traceback. It seems like dRep isn't able to find your files at all? Specially, it's saying `/concatenatedASSVirs/04042019_concatenated_VirSorter_output_for_dRep_cats123/assembly.fasta` is not a file. Could you try something like `head  /concatenatedASSVirs/04042019_concatenated_VirSorter_output_for_dRep_cats123/assembly.fasta` to make sure 1) that path is correct and leads to a real file. If not, something might have gotten messed up when submitting the job to the queue or something like that, and 2) if that file does exist, is it empty? 

Best,
-Matt
