### ISSUE TITLE
pandas error in MASH clustering

### ISSUE THREAD

**Issue by nvpatin** [MrOlm/drep#59]
I am getting the following error with MASH v1.1.1 and dRep v2.3.2 (Python v3.4.5) during step 2a (clustering) step:
Traceback (most recent call last):
  File "/nv/hp10/npatin3/.conda/envs/drep/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/drep/d_workflows.py", line 36, in dereplicate_wrapper
    drep.d_cluster.d_cluster_wrapper(wd, **kwargs)
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/drep/d_cluster.py", line 78, in d_cluster_wrapper
    data_folder, wd=workDirectory, **kwargs)
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/drep/d_cluster.py", line 168, in cluster_genomes
    Mdb = all_vs_all_MASH(Bdb, data_folder, **kwargs)
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/drep/d_cluster.py", line 573, in all_vs_all_MASH
    Mdb = pd.read_csv(file, names=iniCols, usecols=uCols, dtype=dTypes, sep='\t')
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/pandas/io/parsers.py", line 315, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/pandas/io/parsers.py", line 645, in __init__
    self._make_engine(self.engine)
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/pandas/io/parsers.py", line 799, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/nv/hp10/npatin3/.conda/envs/drep/lib/python3.4/site-packages/pandas/io/parsers.py", line 1213, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 470, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4625)
TypeError: data type "category" not understood

This seems to be a pandas issue? I've used Mash on this system before as a standalone program. Any help would be appreciated!

-Nastassia

**Comment by MrOlm** [comment]
Hi Nastassia-

That is a weird error- it seems to be coming from pandas as you suggest. Is it possible that you have an old version of pandas? Could you try `pip install pandas --upgrade` to make sure pandas is up to date and try again?

Best,
Matt

**Comment by nvpatin** [comment]
Thanks Matt, that worked! I'm surprised pandas worked fine with Mash alone but not with dRep...I got a bunch of Matplotlib deprecation warnings but I believe everything ran to completion. Will let you know if not.

**Comment by MrOlm** [comment]
Great! Glad its working now
