### ISSUE TITLE
error of run_tax  option 

### ISSUE THREAD

**Issue by chen318liang** [MrOlm/drep#91]
The error is below. 
the commands is 
dRep dereplicate  test/drep -g test/reassembled_bins/*fa -pa 0.9 -sa 0.95 -nc 0.30 -cm larger -comp 70 -con 10 -p 80 --run_tax

***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Running checkM
100.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Clustering Step 1. Parse Arguments
Clustering Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
47 primary clusters made
Step 3. Perform secondary clustering
Running 47 ANImf comparisons- should take ~ 0.3 min
Step 4. Return output
***************************************************
    ..:: dRep dereplicate Step 3. Choose ::..
***************************************************
    
Loading work directory
***************************************************
    ..:: dRep dereplicate Step 4. Bonus ::..
***************************************************
    
Loading work directory
Running tax
Past prodigal runs found- will not re-run
Running Centrifuge
Traceback (most recent call last):
  File "/software_users/chenliang/miniconda3/envs/drep/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/software_users/chenliang/miniconda3/envs/drep/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/software_users/chenliang/miniconda3/envs/drep/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/software_users/chenliang/miniconda3/envs/drep/lib/python3.6/site-packages/drep/d_workflows.py", line 52, in dereplicate_wrapper
    drep.d_bonus.d_bonus_wrapper(wd, **kwargs)
  File "/software_users/chenliang/miniconda3/envs/drep/lib/python3.6/site-packages/drep/d_bonus.py", line 26, in d_bonus_wrapper
    run_taxonomy(wd,**kwargs)
  File "/software_users/chenliang/miniconda3/envs/drep/lib/python3.6/site-packages/drep/d_bonus.py", line 36, in run_taxonomy
    run_centrifuge(Bdb, prod_dir, cent_dir, wd=wd, **kwargs)
  File "/software_users/chenliang/miniconda3/envs/drep/lib/python3.6/site-packages/drep/d_bonus.py", line 139, in run_centrifuge
    logging.debug(' '.join(cmd))
TypeError: sequence item 3: expected str instance, NoneType found

**Comment by MrOlm** [comment]
Hello,

Can I ask what version of dRep you are running?

Best,
Matt

**Comment by chen318liang** [comment]
> Hello,
> 
> Can I ask what version of dRep you are running?
> 
> Best,
> Matt
The version of dRep is v2.6.2. I install deep using conda, but the default channels can not connect in china. so I delete the channel when installing it. I do not know whether it could affect the versions of some dependencies.

**Comment by MrOlm** [comment]
Hello,

It looks like you didn't provide a centrifuge index as part of your command, which is required to run taxonomy with dRep. I wouldn't recommend it anyways though, the taxonomy generated from centrifuge isn't very accurate anyways. I would recommend another tool like GTDB.

Best,
Matt
