### ISSUE TITLE
CheckM fails

### ISSUE THREAD

**Issue by jtamames** [MrOlm/drep#93]
Hello
Congrats for your nice tool! I am trying it but I cannot make checkM work. The log says:

```
10-07 15:17 DEBUG    ***Logger started up at /media/disk5/tamames/drep/out/log/logger.log***
10-07 15:17 DEBUG    Command to run dRep was: /home/tamames/drep dereplicate drep/out -g drep/maxbin.001.fasta.H1.fasta drep/maxbin.001.fasta.IT11.fasta drep/maxbin.002.fasta.H10.fasta drep/maxbin.002.fasta.IT11.fasta drep/maxbin.002.fasta_sub.IT1.fasta drep/maxbin.003.fasta.H10.fasta drep/maxbin.003.fasta.H1.fasta drep/maxbin.004.fasta.H1.fasta drep/maxbin.005.fasta.H1.fasta drep/maxbin.005.fasta.IT11.fasta drep/maxbin.006.fasta.H10.fasta drep/maxbin.006.fasta.H1.fasta drep/maxbin.008.fasta.H10.fasta drep/maxbin.009.fasta.H10.fasta drep/maxbin.010.fasta.H10.fasta drep/maxbin.010.fasta.H1.fasta drep/maxbin.011.fasta.H10.fasta drep/maxbin.011.fasta.H1.fasta drep/maxbin.012.fasta.H10.fasta drep/maxbin.013.fasta.H10.fasta drep/maxbin.014.fasta.H10.fasta drep/maxbin.016.fasta.H10.fasta drep/maxbin.017.fasta.H10.fasta drep/maxbin.017.fasta_sub.H1.fasta drep/maxbin.018.fasta.H1.fasta drep/maxbin.020.fasta.H10.fasta drep/maxbin.021.fasta.H10.fasta drep/maxbin.021.fasta.H1.fasta drep/maxbin.022.fasta.H10.fasta drep/maxbin.023.fasta.H10.fasta drep/maxbin.024.fasta.H1.fasta drep/maxbin.025.fasta.H10.fasta drep/maxbin.028.fasta.H10.fasta drep/maxbin.029.fasta.H10.fasta drep/maxbin.030.fasta.H10.fasta drep/maxbin.037.fasta.H10.fasta drep/maxbin.038.fasta.H10.fasta drep/maxbin.040.fasta.H10.fasta drep/maxbin.041.fasta.H10.fasta drep/maxbin.049.fasta.H10.fasta drep/maxbin.055.fasta.H10.fasta drep/maxbin.056.fasta_sub.H10.fasta drep/maxbin.057.fasta.H10.fasta drep/maxbin.059.fasta_sub.H10.fasta drep/maxbin.060.fasta.H10.fasta drep/maxbin.063.fasta.H10.fasta drep/maxbin.065.fasta.H10.fasta drep/maxbin.068.fasta.H10.fasta drep/maxbin.073.fasta.H10.fasta drep/maxbin.075.fasta.H10.fasta drep/maxbin.079.fasta.H10.fasta drep/maxbin.083.fasta.H10.fasta drep/maxbin.084.fasta.H10.fasta drep/maxbin.089.fasta.H10.fasta drep/maxbin.090.fasta.H10.fasta drep/maxbin.097.fasta.H10.fasta drep/maxbin.099.fasta.H10.fasta drep/maxbin.102.fasta.H10.fasta drep/maxbin.104.fasta.H10.fasta drep/maxbin.105.fasta.H10.fasta drep/metabat2.19.fa.H10.fasta drep/metabat2.2.fa.H1.fasta drep/metabat2.2.fa.IT1.fasta drep/metabat2.38.fa.H10.fasta drep/metabat2.6.fa.H10.fasta drep/metabat2.75.fa.H10.fasta drep/metabat2.8.fa.H1.fasta --debug

10-07 15:17 DEBUG    dRep version 2.6.2 was run 

10-07 15:17 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

10-07 15:17 DEBUG    Namespace(MASH_sketch=1000, N50_weight=0.5, P_ani=0.9, S_algorithm='ANImf', S_ani=0.99, SkipMash=False, SkipSecondary=False, cent_index=None, checkM_method='lineage_wf', clusterAlg='average', completeness=75, completeness_weight=1, contamination=25, contamination_weight=5, cov_thresh=0.1, coverage_method='larger', debug=True, genomeInfo=None, genomes=['drep/maxbin.001.fasta.H1.fasta', 'drep/maxbin.001.fasta.IT11.fasta', 'drep/maxbin.002.fasta.H10.fasta', 'drep/maxbin.002.fasta.IT11.fasta', 'drep/maxbin.002.fasta_sub.IT1.fasta', 'drep/maxbin.003.fasta.H10.fasta', 'drep/maxbin.003.fasta.H1.fasta', 'drep/maxbin.004.fasta.H1.fasta', 'drep/maxbin.005.fasta.H1.fasta', 'drep/maxbin.005.fasta.IT11.fasta', 'drep/maxbin.006.fasta.H10.fasta', 'drep/maxbin.006.fasta.H1.fasta', 'drep/maxbin.008.fasta.H10.fasta', 'drep/maxbin.009.fasta.H10.fasta', 'drep/maxbin.010.fasta.H10.fasta', 'drep/maxbin.010.fasta.H1.fasta', 'drep/maxbin.011.fasta.H10.fasta', 'drep/maxbin.011.fasta.H1.fasta', 'drep/maxbin.012.fasta.H10.fasta', 'drep/maxbin.013.fasta.H10.fasta', 'drep/maxbin.014.fasta.H10.fasta', 'drep/maxbin.016.fasta.H10.fasta', 'drep/maxbin.017.fasta.H10.fasta', 'drep/maxbin.017.fasta_sub.H1.fasta', 'drep/maxbin.018.fasta.H1.fasta', 'drep/maxbin.020.fasta.H10.fasta', 'drep/maxbin.021.fasta.H10.fasta', 'drep/maxbin.021.fasta.H1.fasta', 'drep/maxbin.022.fasta.H10.fasta', 'drep/maxbin.023.fasta.H10.fasta', 'drep/maxbin.024.fasta.H1.fasta', 'drep/maxbin.025.fasta.H10.fasta', 'drep/maxbin.028.fasta.H10.fasta', 'drep/maxbin.029.fasta.H10.fasta', 'drep/maxbin.030.fasta.H10.fasta', 'drep/maxbin.037.fasta.H10.fasta', 'drep/maxbin.038.fasta.H10.fasta', 'drep/maxbin.040.fasta.H10.fasta', 'drep/maxbin.041.fasta.H10.fasta', 'drep/maxbin.049.fasta.H10.fasta', 'drep/maxbin.055.fasta.H10.fasta', 'drep/maxbin.056.fasta_sub.H10.fasta', 'drep/maxbin.057.fasta.H10.fasta', 'drep/maxbin.059.fasta_sub.H10.fasta', 'drep/maxbin.060.fasta.H10.fasta', 'drep/maxbin.063.fasta.H10.fasta', 'drep/maxbin.065.fasta.H10.fasta', 'drep/maxbin.068.fasta.H10.fasta', 'drep/maxbin.073.fasta.H10.fasta', 'drep/maxbin.075.fasta.H10.fasta', 'drep/maxbin.079.fasta.H10.fasta', 'drep/maxbin.083.fasta.H10.fasta', 'drep/maxbin.084.fasta.H10.fasta', 'drep/maxbin.089.fasta.H10.fasta', 'drep/maxbin.090.fasta.H10.fasta', 'drep/maxbin.097.fasta.H10.fasta', 'drep/maxbin.099.fasta.H10.fasta', 'drep/maxbin.102.fasta.H10.fasta', 'drep/maxbin.104.fasta.H10.fasta', 'drep/maxbin.105.fasta.H10.fasta', 'drep/metabat2.19.fa.H10.fasta', 'drep/metabat2.2.fa.H1.fasta', 'drep/metabat2.2.fa.IT1.fasta', 'drep/metabat2.38.fa.H10.fasta', 'drep/metabat2.6.fa.H10.fasta', 'drep/metabat2.75.fa.H10.fasta', 'drep/metabat2.8.fa.H1.fasta'], ignoreGenomeQuality=False, length=50000, n_PRESET='normal', operation='dereplicate', percent='50', processors=6, run_tax=False, size_weight=0, strain_heterogeneity_weight=1, tax_method='percent', warn_aln=0.25, warn_dist=0.25, warn_sim=0.98, work_directory='drep/out')
10-07 15:17 DEBUG    Starting the dereplicate operation
10-07 15:17 INFO     ***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
10-07 15:17 DEBUG    Loading work directory in filter
10-07 15:17 DEBUG    Located: /media/disk5/tamames/drep/out
Datatables: []
Cluster files: []
Arguments: []
10-07 15:17 DEBUG    Validating filter arguments
10-07 15:17 INFO     Will filter the genome list
10-07 15:18 INFO     Calculating genome info of genomes
10-07 15:18 DEBUG    Filtering genomes by size
10-07 15:18 INFO     100.00% of genomes passed length filtering
10-07 15:18 DEBUG    Running CheckM
10-07 15:18 INFO     Running prodigal
10-07 15:18 INFO     Past prodigal runs found- will not re-run
10-07 15:18 INFO     Running checkM
10-07 15:18 DEBUG    Running CheckM with command: ['/media/disk5/tamames/SqueezeMeta/bin/checkm', 'lineage_wf', '/media/disk5/tamames/drep/out/data/prodigal/', '/media/disk5/tamames/drep/out/data/checkM/checkM_outdir/', '-f', '/media/disk5/tamames/drep/out/data/checkM/checkM_outdir//results.tsv', '--tab_table', '-t', '6', '--pplacer_threads', '6', '-g', '-x', 'faa']
10-07 15:18 DEBUG    Running CheckM with command: ['/media/disk5/tamames/SqueezeMeta/bin/checkm', 'qa', '/media/disk5/tamames/drep/out/data/checkM/checkM_outdir/lineage.ms', '/media/disk5/tamames/drep/out/data/checkM/checkM_outdir/', '-f', '/media/disk5/tamames/drep/out/data/checkM/checkM_outdir/Chdb.tsv', '-t', '6', '--tab_table', '-o', '2']
10-07 15:18 ERROR    !!! checkM failed !!!
```
In addition, STDERR says:

```
*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
Traceback (most recent call last):
  File "/media/disk5/tamames/SqueezeMeta/bin/checkm", line 718, in <module>
    checkmParser.parseOptions(args)
  File "/media/disk5/tamames/SqueezeMeta/bin/../lib/checkm/main.py", line 1243, in parseOptions
    self.qa(options)
  File "/media/disk5/tamames/SqueezeMeta/bin/../lib/checkm/main.py", line 396, in qa
    binIdToModels = markerSetParser.loadBinModels(hmmModelInfoFile)
  File "/media/disk5/tamames/SqueezeMeta/bin/../lib/checkm/markerSets.py", line 537, in loadBinModels
    with gzip.open(filename, 'rb') as f:
  File "/usr/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/media/disk5/tamames/drep/out/data/checkM/checkM_outdir/storage/checkm_hmm_info.pkl.gz'

```
I checked and the file `/media/disk5/tamames/drep/out/data/checkM/checkM_outdir/storage/checkm_hmm_info.pkl.gz` is indeed not present.  Nevertheless, checkM is working fine indepently, and seems to be properly configured:

```
Loading work directory
Checking dependencies
mash.................................... all good        (location = /usr/bin/mash)
nucmer.................................. all good        (location = /usr/bin/nucmer)
checkm.................................. all good        (location = /media/disk5/tamames/SqueezeMeta/bin/checkm)
ANIcalculator........................... !!! ERROR !!!   (location = None)
prodigal................................ all good        (location = /usr/local/bin/prodigal)
centrifuge.............................. !!! ERROR !!!   (location = None)
nsimscan................................ !!! ERROR !!!   (location = None)
fastANI................................. !!! ERROR !!!   (location = None)
```
I will appreciate very much any help. Thanks a lot!
Best,
Javier

**Comment by MrOlm** [comment]
Hi Javier,

A couple of things. 

1) That STDOUT error actually isn't relevant in this case. dRep runs checkM in two steps, with the second step reliant on the first. This is the error that you get when the first step fails. The step that checkM is actually failing on is:

```
Running CheckM with command: ['/media/disk5/tamames/SqueezeMeta/bin/checkm', 'lineage_wf', '/media/disk5/tamames/drep/out/data/prodigal/', '/media/disk5/tamames/drep/out/data/checkM/checkM_outdir/', '-f', '/media/disk5/tamames/drep/out/data/checkM/checkM_outdir//results.tsv', '--tab_table', '-t', '6', '--pplacer_threads', '6', '-g', '-x', 'faa']
```

which I just got from your log file.

2) In order to see the error code that is being thrown to make this step crash, you can re-run dRep with the `-d` flag. This will make a folder called `cmd_logs` in the `log` directory of dRep, and in there you'll find the error code that checkM is giving that's causing this first step to fail.

3) It looks like you're running dRep on the same directory multiple times in a row. This is fine and usually works, but there are also weird bugs that sometimes happen when you do this, so I would suggest running dRep fresh with a new workdirectory to see if that fixes the problem.

4) If all else fails and you're not able to fix this problem, you can always run checkM on your own on this genome set, and give the results to dRep with the flag `--genomeInfo`

Hope that helps and let me know if you have any other questions!
-Matt
